### ISSUE TITLE
Community Diligence Review of Bewell Technology Limited Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#10]
Review of Top Value Allocations from @Aaron01230
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/992

First example:
DataCap was given to:
https://github.com/filplus-bookkeeping/Bewell-Technology-Limited/issues/1
Public Open Dataset - key compliance requirement: Retrievability

1st point)
Allocation schedule unclear of the details in allocator application notes to do a comparison but the allocator awarded this client three times with 500TiB, 1PiB, 2PiB

2nd point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application. Questions were asked about previous applications in LDN and also data preparation

3rd point)
Client said these were the SPs, no entity, no location. No comment from Allocator about this
f02945258
f02941878
f02941888 
f02941882 
f02941891 
f02941885
f02941886  
f02945259
f02950965
f02830476
f02830451

Actual data storage report:
https://check.allocator.tech/report/filplus-bookkeeping/Bewell-Technology-Limited/issues/1/1715264125065.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
f03028326 | Shenzhen, Guangdong, CNCTGNet | 325.56 TiB | 14.43% | 325.56 TiB | 0.00%
f02830476 | Shenzhen, Guangdong, CNCTGNet | 93.50 TiB | 4.14% | 93.50 TiB | 0.00%
f03071472 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 400.41 TiB | 17.74% | 400.41 TiB | 0.00%
f03028321 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 285.88 TiB | 12.67% | 285.88 TiB | 0.00%
f03028315 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 285.84 TiB | 12.67% | 285.84 TiB | 0.00%
f03028310 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 284.78 TiB | 12.62% | 284.78 TiB | 0.00%
f03028318 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 270.69 TiB | 11.99% | 270.69 TiB | 0.00%
f03028325 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 267.16 TiB | 11.84% | 267.13 TiB | 0.01%
f01943663 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 34.50 TiB | 1.53% | 34.50 TiB | 0.00%
f01928097 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 8.38 TiB | 0.37% | 8.38 TiB | 0.00%

One SP IDs taking deals matches per report. All others were not reported and with unknown details. Looks to be centrailzed in one location
, but additional diligence needed to confirm entity and actual storage locations 

3rd point)
Second, third allocation awarded to this client.
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability.

The Allocator showed no sign of diligence after 1st allocation and gave the 2nd, 3rd allocation of 3.6PiB to the client.

**Comment by filecoin-watchdog** [comment]
Second example:
DataCap was given to: https://github.com/filplus-bookkeeping/Bewell-Technology-Limited/issues/3
Public Open Dataset - key compliance requirement: Retrievability

1st point)
No client KYC or KYB. Allocator asked for KYC after two allocation (1PiB) given. Response was an email screenshot. https://github.com/filplus-bookkeeping/Bewell-Technology-Limited/issues/3#issuecomment-2094644505. Does not match what was said was diligence in application of allocator

2nd point) SPs listed in client application:
f02850067
fo2830476
fo2941888
fo2950965
fo2830451

report listing SPs taking deals: https://check.allocator.tech/report/filplus-bookkeeping/Bewell-Technology-Limited/issues/3/1715264582659.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
f02830476 | Shenzhen, Guangdong, CNCTGNet | 12.97 TiB | 1.32% | 12.97 TiB | 0.00%
f03028325 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 195.31 TiB | 19.94% | 195.31 TiB | 0.00%
f03028315 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 195.31 TiB | 19.94% | 195.31 TiB | 0.00%
f03028318 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 195.31 TiB | 19.94% | 195.31 TiB | 0.00%
f03028321 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 195.28 TiB | 19.93% | 195.28 TiB | 0.00%
f03028310 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 173.03 TiB | 17.66% | 173.03 TiB | 0.00%
f01928097 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 12.47 TiB | 1.27% | 12.47 TiB | 0.00%

One SP matches from original list, and is storing 1%. All others unknown, need more diligence to verify location and entity

3rd point)
Second allocation awarded to this client.
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability.

The Allocator showed no sign of diligence after 1st allocation and gave the 2nd, total 1PiB allocated.














Provider	Location	Total Deals Sealed	Percentage	Unique Data	Duplicate Deals
[f02830476](https://filfox.info/en/address/f02830476)	Shenzhen, Guangdong, CN
CTGNet	12.97 TiB	1.32%	12.97 TiB	0.00%
[f03028325](https://filfox.info/en/address/f03028325)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	195.31 TiB	19.94%	195.31 TiB	0.00%
[f03028315](https://filfox.info/en/address/f03028315)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	195.31 TiB	19.94%	195.31 TiB	0.00%
[f03028318](https://filfox.info/en/address/f03028318)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	195.31 TiB	19.94%	195.31 TiB	0.00%
[f03028321](https://filfox.info/en/address/f03028321)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	195.28 TiB	19.93%	195.28 TiB	0.00%
[f03028310](https://filfox.info/en/address/f03028310)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	173.03 TiB	17.66%	173.03 TiB	0.00%
[f01928097](https://filfox.info/en/address/f01928097)	Hong Kong, Hong Kong, HK
Hong Kong Beecloud System Technology Services Limited	12.47 TiB	1.27%	12.47 TiB	0.00%

**Comment by filecoin-watchdog** [comment]
Interesting note:
Exact same set of unknown SPs used on both applications with no retrievability.

**Comment by Kevin-FF-USA** [comment]
Hi @Aaron01230

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/10.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/8b63247e-880b-43fe-8473-814ce838a549)

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is **not** in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/992).

Specifically: 

- No evidence of diligence with client (no verification of client claims)
- Allocations did not match tranche schedule (not scaling trust over time)
- Subsequent allocations given despite noncompliant client deal-making (no verification of data legitimacy)
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

**Given these details, this allocator will not receive a subsequent allocation request to the root key holders at this time.**

**Comment by Aaron01230** [comment]
Sorry, we have been busy with other things recently and have not paid attention to this. We have communicated with SPs and they do not support Spark retrieval because they use Venus service for packaging. They will support HTTP retrieval in the future.
