### ISSUE TITLE
Community Diligence Review of Data Preservation (FIDL Team) Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#106]
Allocator Compliance Report:
https://compliance.allocator.tech/report/f03015757/1721397084/report.md

Review of Allocations from Data Preservation
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/997

First example:
DataCap was given to: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/18

Enterprise Data (private) and 2 copies required

KYC/KYB completed for this client and GitHub ID: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/18#issuecomment-2043189544

Allocation distribution matched allocator guidelines: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/18#issuecomment-2110200779

SPs provided
f02927579 | KABAT OU/FILDC | Poland, Łódź, Europe
f02770730 | KABAT OU/FILDC | Poland, Poznań, Europe
f01619524 | Flux Storage Pte. Ltd | Germany, Frankfurt am Main, Europe
f099608 | Private/Stander | Latvia, Riga, Europe
f020378 | Web3 providers LLC | Bulgaria, Asenovgrad, Europe
f01222595, f0187709 | Saturnia | Moscow, Russian Federation

SPs taking deals https://check.allocator.tech/report/fidlabs/Enterprise-Data-Pathway/issues/18/1721398411902.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f01127678 | Poznań, Greater Poland, PLBeyond.pl sp. z o.o. | 521.16 TiB | 33.16% | 521.16 TiB | 0.00% | 0.00%
f02770730 | Poznań, Greater Poland, PLBeyond.pl sp. z o.o. | 81.50 TiB | 5.19% | 81.50 TiB | 0.00% | 0.00%
f099608 | Riga, Riga, LVJSC BALTICOM | 5.97 TiB | 0.38% | 5.97 TiB | 0.00% | 0.00%
f01619524 | Frankfurt am Main, Hesse, DEMichael Sebastian Schinzel trading as IP-Projects GmbH & Co. KG | 229.86 TiB | 14.63% | 229.02 TiB | 0.37% | 0.00%
f0187709 | Moscow, Moscow, RUMTS PJSC | 191.46 TiB | 12.18% | 191.46 TiB | 0.00% | 84.71%
f01222595 | Moscow, Moscow, RUPJSC "Vimpelcom" | 335.98 TiB | 21.38% | 334.89 TiB | 0.33% | 72.59%
f02927579 | Łódź, Łódź Voivodeship, PLTPnets.com Sp. z o.o. | 205.48 TiB | 13.08% | 205.48 TiB | 0.00% | 0.00%

SP Distribution looks good.

**Comment by filecoin-watchdog** [comment]
Second example: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22

Enterprise private data.

KYC/KYB completed for client: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22#issuecomment-2061096779

CID report: https://check.allocator.tech/report/fidlabs/Enterprise-Data-Pathway/issues/22/1721399033355.md

SP Distribution looks good, was clarified by client: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22#issuecomment-2137598068

Allocations match what Allocator said

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/997)

We are requesting **10PiB of DataCap from RKH** for this pathway to increase runway and scale.


KevZak: Please reply if there are any issues, concerns, or updates while we initiate the request to the RKH.
