### ISSUE TITLE
2nd Community Diligence Review of RFfil Allocator 

### ISSUE THREAD

**Issue by MikeH1999** [filecoin-project/Allocator-Governance#117]
Allocator report:
https://compliance.allocator.tech/report/f03014594/1721893882/report.md

First diligence review: https://github.com/filecoin-project/Allocator-Governance/issues/11

Newly added sp all support spark retrieval

**Comment by filecoin-watchdog** [comment]
@MikeH1999 based on your last review

**Comment by filecoin-watchdog** [comment]
It looks like the recent 2.5 Pibs has been given all to a previous client that has:

- really not shown any proof of 1PiB of Dataset - data provided is MBs https://drive.google.com/drive/folders/1rJvCYROC5m35_GyISvHBXIoRQflhvyzd?usp=sharing

- continued adding SPs that were not on the original list 

- storing across 11 SPs when they said they wanted 5 copies

- has been given almost 5PiBs (they amount they asked) and has stored only 624TiBs of unique data

**Comment by filecoin-watchdog** [comment]
This is reflective of good deal making? 

Can we even retrieve the data? 

Has there been any information provided by SPs to enable client (or anyone) to download the CAR files?

**Comment by MikeH1999** [comment]
> It looks like the recent 2.5 Pibs has been given all to a previous client that has:
> 
> * really not shown any proof of 1PiB of Dataset - data provided is MBs https://drive.google.com/drive/folders/1rJvCYROC5m35_GyISvHBXIoRQflhvyzd?usp=sharing

This was confirmed by video at the beginning of the review, here is a translation of the screenshot，[Here's the original comment](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2019338602)
![image](https://github.com/user-attachments/assets/70a52ece-5818-4d12-abf6-bb17ea71a903)

> * continued adding SPs that were not on the original list

Following the STFIL incident, the latest SP client to work with has stated by way of comment that
[Comment 1 ](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2134217357)[Comment 2](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2134411882)
![image](https://github.com/user-attachments/assets/771e3170-1e36-4f74-9237-ec37bf7d8e5f)

After the above miners were sealed, I did a manual retrieval since spark didn't support allocator paths at the time，[The comments are here.](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2146478313)

Customers are adding new SPs again，[Second time](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2208659026) 

[ Third time](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2232486294)
In this addition of sp, since the sp is not in China, I performed geolocation verification
![image](https://github.com/user-attachments/assets/f28358e9-561d-4fd5-a345-00c55c47348f)

The list of published sps before the stfil event is as follows，Most SPs termination of all sectors due to stfil events
f02519100 GuangZhou
f02215209 Californial
f02770938 HongKong
f02093396 Singapore
f02259777 Singapore
f02237006 Singapore
f03034045 Tokyo

The list of subsequent sps added is as follows
f0872282,f02822222 York Hong Kong
f01888808 Zheng Jianlin Romania
f01930832 zhao nanjin
f01390330，f02899169 tiger xian
f02820000 GuangZhou
f02639655 GuangZhou
f02866666 Tokyo
f03144777 Tokyo

No undisclosed sp in the latest report

> * storing across 11 SPs when they said they wanted 5 copies

I also asked the client before this and the review[ is here](https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2251952567), screenshot below
![image](https://github.com/user-attachments/assets/284e8a05-ef80-4b6a-b675-3c4d61ae6857)

> * has been given almost 5PiBs (they amount they asked) and has stored only 624TiBs of unique data

More than 2PiB of datacap had been allocated prior to the stfil event, so this resulted in subsequent allocations of datacap not being able to fully sequester subsequent unique data while keeping the robot reporting healthy.

From here it seems that the stfil event can't be underestimated in terms of its impact on filecoin

**Comment by MikeH1999** [comment]
> This is reflective of good deal making?
> 
> Can we even retrieve the data?
> 
> Has there been any information provided by SPs to enable client (or anyone) to download the CAR files?

The list of published sps before the stfil event is as follows，Most SPs termination of all sectors due to stfil events
f02519100 GuangZhou
f02215209 Californial
f02770938 HongKong
f02093396 Singapore
f02259777 Singapore
f02237006 Singapore
f03034045 Tokyo

The list of subsequent sps added is as follows
f0872282,f02822222 York Hong Kong
f01888808 Zheng Jianlin Romania
f01930832 zhao nanjin
f01390330，f02899169 tiger xian
f02820000 GuangZhou
f02639655 GuangZhou
f02866666 Tokyo
f03144777 Tokyo

Check out this list, pre-stfil events may not be retrievable, but subsequent SPs support spark retrieval

**Comment by MikeH1999** [comment]
> I'm wondering what you did differently with the more recent 2.5PiB allocation?
@filecoin-watchdog 
- During this period, I assisted the client in doing a lot of testing on the support for spark retrieval, and then the client's SPs all support spark retrieval, except for the use of the vunes tool.
- After being affected by the stfil incident,  assisting that client to gradually move from unhealthy reports of robots to healthy
beginning
![image](https://github.com/user-attachments/assets/bdd6ec51-cf8c-426f-aa7e-4c530875eaa1)

now
![image](https://github.com/user-attachments/assets/4378c962-d746-4f90-a133-a9861d4ca4de)

**Comment by MikeH1999** [comment]
If you have any other questions, please feel free to leave a message!

**Comment by MikeH1999** [comment]
If there is something wrong in the middle, welcome to point it out!

**Comment by MikeH1999** [comment]
sp affected by the stfil incident，Mostly no retrieval rate
f02519100 GuangZhou
f02215209 Californial
f02770938 HongKong
f02093396 Singapore
f02259777 Singapore
f02237006 Singapore
f03034045 Tokyo

The list of subsequent sps added is as follows
f0872282,f02822222 York Hong Kong
f01888808 Zheng Jianlin Romania
f01930832 zhao nanjin
f01390330，f02899169 tiger xian
f02820000 GuangZhou
f02639655 GuangZhou
f02866666 Tokyo
f03144777 Tokyo
Most of them support spark retrieval
![image](https://github.com/user-attachments/assets/fe6beaab-0d6b-4e1d-ba33-8175da7e0b1b)

**Comment by MikeH1999** [comment]
After the new version, it was found that some of the retrieval rates have been dropping, and we are currently assisting the customer to contact the spark team to deal with it

**Comment by MikeH1999** [comment]
After talking to Miroslav Bajtoš, a member of the spark team, the problem has been largely identified, and we believe that the retrieval rate will improve soon!
![image](https://github.com/user-attachments/assets/c074251a-68de-4d1e-8050-376aa7754df3)

**Comment by MikeH1999** [comment]
Seeing a steady increase in retrieval rates so far
![image](https://github.com/user-attachments/assets/3396b743-4a6b-4701-a26a-b46ee99508be)

**Comment by MikeH1999** [comment]
> Hi Mike - we think its also important for your clients to start providing more information about data preparation - see a proposal I submitted #125 any thoughts?

Hi  kz  -I'm on vacation for a while, so I'll check it out later

**Comment by MikeH1999** [comment]
> Seeing a steady increase in retrieval rates so far ![image](https://private-user-images.githubusercontent.com/149572051/356952857-3396b743-4a6b-4701-a26a-b46ee99508be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTkzMTMsIm5iZiI6MTcyNDA1OTAxMywicGF0aCI6Ii8xNDk1NzIwNTEvMzU2OTUyODU3LTMzOTZiNzQzLTRhNmItNDcwMS1hMjZhLWI0NmVlOTk1MDhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmM3ZGY4MGEyNzllNTQ5ODVkOTc4OGUyY2JmOWZkNjYyNDY5NDk1OTcxZDZlMmU4M2E4NDZiNGM2YTQ2YzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fmSvDCxj300Xj2GHQL8bCp2GS40_rr8A8_i9HNoUMUA)

Retrieval rates have been steadily increasing through the assistance of the spark team
![image](https://github.com/user-attachments/assets/4d89e42b-d6dd-4455-abf3-85820a7aab8d)

**Comment by MikeH1999** [comment]
> Seeing a steady increase in retrieval rates so far ![image](https://private-user-images.githubusercontent.com/149572051/356952857-3396b743-4a6b-4701-a26a-b46ee99508be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTkzMTMsIm5iZiI6MTcyNDA1OTAxMywicGF0aCI6Ii8xNDk1NzIwNTEvMzU2OTUyODU3LTMzOTZiNzQzLTRhNmItNDcwMS1hMjZhLWI0NmVlOTk1MDhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmM3ZGY4MGEyNzllNTQ5ODVkOTc4OGUyY2JmOWZkNjYyNDY5NDk1OTcxZDZlMmU4M2E4NDZiNGM2YTQ2YzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fmSvDCxj300Xj2GHQL8bCp2GS40_rr8A8_i9HNoUMUA)

Retrieval rates have been steadily increasing through the assistance of the spark team
![image](https://github.com/user-attachments/assets/6e511ebb-98ba-470d-a34d-25028e87e7da)

**Comment by MikeH1999** [comment]
![image](https://github.com/user-attachments/assets/7ea35d1f-afc2-4821-82f0-d83cda2e9ac9)
Here's the data for the last 24 hours. Looks good.

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is partially in compliance and making efforts to improve. From the claims, their clients and SPs were impacted by the STFIL incident, which may have accounted for the low retrievals.  Seeing increasing activity and work with clients to improve the Spark retrievability, but will be held to maintaining that standard. 

Given this mixed review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 5 PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

@mikeh1999  can you verify that you will enforce program and allocator requirements? 
(for example: public diligence, tranche schedules, and public scale retrievability like Spark). Please reply here with acknowledgement and any additional details for our review.

**Comment by MikeH1999** [comment]
>@MikeH1999 can you verify that you will enforce program and allocator requirements?
>(for example: public diligence, tranche schedules, and public scale retrievability like Spark). Please reply here with acknowledgement and any additional details for our review.

I confirm. Thank you for reviewing.

**Comment by MikeH1999** [comment]
https://github.com/MikeH1999/RFfil/issues/41
Here is a review of one of my latest clients, please refer to the

**Comment by MikeH1999** [comment]
Regarding the retrievability reference [this comment](https://github.com/filecoin-project/Allocator-Governance/issues/117#issuecomment-2277895546) that has been assisting the client and the SPARK team with retrieval rate checking as well as maintenance

**Comment by MikeH1999** [comment]
@galen-mcandrew Thank you for your reply.

**Comment by Kevin-FF-USA** [comment]
DataCap Issued: https://filecoinpulse.pages.dev/allocator/f03014594/#pageparamsallocator_id
Closing Issue
