### ISSUE TITLE
Community Diligence Review of QC_Data_center Allocator 

### ISSUE THREAD

**Issue by luhong123** [filecoin-project/Allocator-Governance#124]
Review of Allocations from QC_Data_center
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1071

All SPs support Spark

First example:
DataCap was given to:
https://github.com/luhong123/QC-Data-center/issues/3

First: 512TiB • Second:1PiB • Third: 1PiB • Fourth:2PiB 
Due diligence was conducted before each signing. Pay close attention to Spark data, SP disclosure, etc.

SP disclosure：
f02363181 Huhehaote
f02368946 Huhehaote
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong
f02822222 Hong Kong
f02588263 Hong Kong

Actual data storage report:
https://check.allocator.tech/report/luhong123/QC-Data-center/issues/3/1722912731582.md
![image](https://github.com/user-attachments/assets/fae00633-1619-4592-9819-6fc5ded7e392)

The client actually sealed 7 SPs, and the latest 2 can already see the retrieval rate on spark
![image](https://github.com/user-attachments/assets/4451cb4f-5c53-47b6-b2a6-35b4d71aa24e)

**Comment by luhong123** [comment]
![image](https://github.com/user-attachments/assets/1812bebe-3169-4b2a-9802-a66dc2f1c391)
Overall retrieval rate looks good

**Comment by kevzak** [comment]
Hi @luhong123  - we think it is important for all clients to start providing more details of data preparation. See my proposal https://github.com/filecoin-project/Allocator-Governance/issues/125 any thoughts?

**Comment by luhong123** [comment]
> Hi @luhong123 - we think it is important for all clients to start providing more details of data preparation. See my proposal #125 any thoughts?

Check back later.

**Comment by Kevin-FF-USA** [comment]
Hello!
Shifting the response and continue of this review into this issue: https://github.com/filecoin-project/Allocator-Governance/issues/140.  Will close this issue (when 140 closes)
