### ISSUE TITLE
2nd Community Diligence Review of Greater Heat Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#130]
[Link to First Review](https://github.com/filecoin-project/Allocator-Governance/issues/14)

Latest Allocator Report: https://compliance.allocator.tech/report/f03010601/1723594199/report.md

Allocator received 10PiBs additional allocation.

DataCap awarded to:
4PIBs https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9
1PiB https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/11
4PiBs https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/7
1PiB https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/15

There are three points across the applications:

1) 5 SPs not on original application SP lists have taken 60% (6PiBs) of new DataCap across the 4 clients. 

2) Across all 4 applications, there is no detail on data preparation, all questions in the applications are left blank. I'd challenge the allocator to push for more details and demonstrate proof of how dataset is prepared and documented and how the client can actually retrieve the open files. See list of questions:
- https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9#issuecomment-2288453698

3) There is no questioning of dataset size and total DataCap calculations [example] (https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9#issuecomment-2288448914) - I would ask the allocator / clients to justify the amount they are asking. 8-10PiBs is a lot for a small sample of 100MBs

**Comment by filecoin-watchdog** [comment]
One additional note: 5PiBs of DataCap has not been used in deals yet. Perhaps its better to complete a review when 75% usage is reached 

https://datacapstats.io/notaries/f03010601

**Comment by AlanGreaterheat** [comment]
Thank you for your patience in reviewing this.

Regarding the first issue: Data storage depends on various factors, such as storage plans, data preparation, DC quotas, technical integration, and Filecoin collateral, all of which need to be adapted individually. The STFIL crisis in March-April this year led many SPs, who originally planned to proceed with data sealing, to temporarily suspend their plans. The borrowing of collateral and the large amount of self-held Filecoin collateral significantly affected the sealing process of SPs. Therefore, it is entirely understandable that SPs may need to make updates during the actual data storage process. At the same time, clients disclose information about the SPs they are communicating with in a timely manner during the application process; if updates are not provided in a timely manner, GreaterHeat also requests further explanations. Detailed records can be found as follows:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/d7cf2069-6af1-423a-b4c3-50c6c797c76e">
<img width="693" alt="image" src="https://github.com/user-attachments/assets/addf359e-9374-46bd-9076-a176e5e191fb">
<img width="701" alt="image" src="https://github.com/user-attachments/assets/f0c25bdf-d852-4508-807c-05ee5bfdbc09">
<img width="693" alt="image" src="https://github.com/user-attachments/assets/553b90ac-dc0d-4fd7-bcf0-ba5fa3cde790">

Regarding the second issue: Each allocator has its own allocation rules. Although clients may not promptly disclose information related to data preparation in their application, GreaterHeat, as an allocator, has conducted further inquiries about data preparation methods in the comment updates. Please see the details below:
<img width="692" alt="image" src="https://github.com/user-attachments/assets/38a8dbab-7546-4a38-8612-b987234d834d">

The inquiry method we used was also inspired by the official due diligence process in the V4 LDN model. However, as noted in the latest issue published by Kevzak: https://github.com/filecoin-project/Allocator-Governance/issues/125, the governance team encountered certain limitations during the review process. We have actively left comments, and as stated in the comments, while compliance verification of data preparation details can be appropriately due-diligenced, the role of the allocator requires a better balance between the convenience of client data onboarding and the effective increase in SPs' computing power. We believe that overly stringent and overly lenient due diligence are both detrimental to the development of the Filecoin ecosystem. Instead, entrusting the decision-making power to the allocator reflects the important role of the allocator.

Regarding the third issue: We carefully reviewed the client’s official website, https://www.youle.com.sg/. As an early education institution, it continuously generates material such as daily teaching videos and children’s daily life videos. The application only includes a sample of this data. According to the original 580TiB of data, there will be some padding conversion rate when converting to CAR files. Based on the calculation, one backup corresponds to approximately 1PiB of data. If there are 10 backups, it aligns with the application for 10PiB.

Finally, each allocator has its unique approval tendencies. As an allocator, GH focuses more on the Spark retrieval success rate of SPs. It is encouraging that, with our continuous requests, the Spark retrieval success rate of SPs is improving. 
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/e97034a6-f90e-4133-bd29-714d645bdb10">

Currently, SPs are still in the sealing process, and we will actively participate in governance meetings, hoping that the second recharge will receive 20PiB of DC support.Thank you very much！

**Comment by AlanGreaterheat** [comment]
@galen-mcandrew @Kevin-FF-USA 
Update: Compared to 2-3 weeks ago, the success rate of SPs (Service Providers) retrieval has continued to improve.

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/7b6acd1e-2bcb-42ba-9aec-36c7f487e852">

**Comment by galen-mcandrew** [comment]
Given the details presented above and some additional investigation into these clients, we are seeing partial compliance. Specifically:

- 28% avg retrievability rate of public open datasets
- High usage of VPNs without enforcing stated requirements from allocator application (https://github.com/filecoin-project/notary-governance/issues/1041#issuecomment-1890597171 "limited use of VPNs"
- Mixed KYC diligence into client claims, such as https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/11 & https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9
- One of the above clients is claiming to be a US-based market research company, but application and SP deal-making do not reflect authenticity of this data owner

Given the overall status of this allocator, we are requesting a matched amount of **10PiB DataCap from RKH.** @AlanGreaterheat Please verify that you will instruct, support, and require your clients to work with compliant storage providers.

**Comment by AlanGreaterheat** [comment]
Thank you for @galen-mcandrew  response. We will pay closer attention to the compliance of the allocator's operations in the future and execute its functions according to official requirements. For example:The Spark retrieval success rate continues to improve , KYC due diligence will be more rigorous and comprehensive,etc.
Looking forward to our joint efforts！

**Comment by Kevin-FF-USA** [comment]
DataCap issued: https://filecoinpulse.pages.dev/allocator/f03010601/#pageparamsallocator_id
Closing Issue
