### ISSUE TITLE
Community Diligence Review of DAYOU Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#135]
Latest Allocator Report: https://compliance.allocator.tech/report/f03019913/1723767049/report.md

Client example 1: 
https://github.com/filplus-bookkeeping/DAYOU/issues/3
https://check.allocator.tech/report/filplus-bookkeeping/DAYOU/issues/3/1717504125835.md

Client asked for 25% Total DataCap requested and was awarded 500TiBs. Allocator was going to give 50. Doesn't match allocator allocation schedule

Client claimed to use a list of SPs but used different SPs /  one SP: https://github.com/filplus-bookkeeping/DAYOU/issues/3#issuecomment-2293485565

Client closed application stating data hasn't been updated and they will apply again. ?? Not sure what that means

**Comment by filecoin-watchdog** [comment]
Client example 2: 
https://github.com/filplus-bookkeeping/DAYOU/issues/6
client provides very little information about themselves as data owner, their data prep plan, the size of their data

https://check.allocator.tech/report/filplus-bookkeeping/DAYOU/issues/6/1723813532276.md
SPs don't match - retrievals extremely low after warning and client continued to receive Data Cap https://github.com/filplus-bookkeeping/DAYOU/issues/6#issuecomment-2293500046

**Comment by filecoin-watchdog** [comment]
Client example 3:
https://github.com/filplus-bookkeeping/DAYOU/issues/9
https://check.allocator.tech/report/filplus-bookkeeping/DAYOU/issues/9/1723813492061.md
low SP match
low retrievals

**Comment by filecoin-watchdog** [comment]
Client example 4:
Client from example 1 reapplied 
https://github.com/filplus-bookkeeping/DAYOU/issues/12
https://check.allocator.tech/report/filplus-bookkeeping/DAYOU/issues/12/1723813487853.md

**Comment by galen-mcandrew** [comment]
Reviewing the above details, we are seeing compliance issues. Specifically:

- Low and inconsistent retrieval of public open datasets
- High usage of VPNs without enforcing stated requirements from allocator application (https://github.com/filecoin-project/notary-governance/issues/1010 "clients need to explicitly disclose the use of a VPN"
- Noncompliant SP distribution (Data Distribution section of application, https://github.com/filecoin-project/notary-governance/issues/1010#issuecomment-1872625481), with continued subsequent allocations (such as https://check.allocator.tech/report/filplus-bookkeeping/DAYOU/issues/6/1724913955384.md)
- Noncompliant DataCap tranche allocations 
- Mixed KYC diligence into client claims, such as clients making conflicting region claims and lacking KYC checks in GitHub (such as https://github.com/filplus-bookkeeping/DAYOU/issues/3)

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

Given this mixed review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an additional **2.5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

Please verify that you will instruct, support, and require your clients to work with retrievable storage providers. @DaYouGroup  can you verify that you will enforce retrieval requirements, such as through Spark?

**Comment by Kevin-FF-USA** [comment]
DataCap refreshed: https://filecoinpulse.pages.dev/allocator/f03019913/
Closing issue
