### ISSUE TITLE
Community Review of Marshall Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#138]
Allocator Compliance Report: https://compliance.allocator.tech/report/f03012911/1724112525/report.md

Example 1: https://github.com/Marshall-btc/Marshall-Fil-Data-Pathway/issues/1

KYC shared in comments - ask gov team to follow up if needed

Public Open Dataset

SPs provided:
f03074583  
f03074586   
f03074587   
f03074589   
f03074592

CID report: https://check.allocator.tech/report/Marshall-btc/Marshall-Fil-Data-Pathway/issues/1/1721956008799.md
SPs used for deals:
Provider	Location	Total Deals Sealed	Percentage	Unique Data	Duplicate Deals	Mean Spark Retrieval Success Rate 7d
[f03055005](https://filfox.info/en/address/f03055005)	Hong Kong, Hong Kong, HK
China Unicom Global	177.94 TiB	35.61%	171.72 TiB	3.49%	0.00%
[f01315096](https://filfox.info/en/address/f01315096)	Hong Kong, Hong Kong, HK
China Unicom Global	51.31 TiB	10.27%	50.47 TiB	1.64%	0.00%
[f03091739](https://filfox.info/en/address/f03091739)	Dallas, Texas, US
Flexential Colorado Corp.	93.84 TiB	18.78%	93.75 TiB	0.10%	0.00%
[f03144037](https://filfox.info/en/address/f03144037)	Paripark, Seoul, KR
The Constant Company, LLC	176.59 TiB	35.34%	176.59 TiB	0.00%	8.57%

No SPs match original list
Retrievals are low across SPs taking deals

Client received 1.3PiBs over 2 allocations

**Comment by filecoin-watchdog** [comment]
Example 2 https://github.com/Marshall-btc/Marshall-Fil-Data-Pathway/issues/3
Example 3 https://github.com/Marshall-btc/Marshall-Fil-Data-Pathway/issues/5

SPs given do not match
Retrievals low, client still given additional 1PIB of Data

Small group of SPs storing 80% of deals

**Comment by filecoin-watchdog** [comment]
Across all 3 applications, there is no detail on data preparation, all questions in the applications are left blank. I'd challenge the allocator to push for more details and demonstrate proof of how dataset is prepared and documented and how the client can actually retrieve the open files. 

There is no questioning of dataset size and total DataCap calculations - I would ask the allocator / clients to justify the amount they are asking. The totals being requested do not match the amounts of the Dataset * the # of copies

**Comment by Marshall-btc** [comment]
I have read the question posed by filecoin-watchdog and wish to respond here.
1. Retrieval Success Rate
I have consistently regarded retrieval as a key issue and believe that the retrieval success rate is a crucial metric. In the fourth round of Fil+ rules, Boost retrieval rate was one of the metrics tested, and now we are more concerned about Spark retrieval rate. In the previous Allocator quota refresh process, Spark was identified as a new retrieval method that requires further study to adapt to different sizes of SPs, particularly for small and medium-sized SPs, which presents a challenge. However, it is evident that the overall retrieval rate of Spark is gradually improving. Please refer to the attached screenshots for more details.
![image](https://github.com/user-attachments/assets/43a5526a-e56e-45ca-bfe9-9e9e736a7a3f)
![image](https://github.com/user-attachments/assets/7a9c970c-b446-4f1e-b5a3-5d8372e24e30)
![image](https://github.com/user-attachments/assets/183d0cb7-476f-46ed-9650-c38c5c2d2d13)
![image](https://github.com/user-attachments/assets/fe478913-40cc-4992-9f35-484be0279cfc)

**Comment by Marshall-btc** [comment]
2. The list of actual participating SPs does not appear in the client application.
I identified this issue at the outset of data distribution and have been in communication with the client on GitHub.
It seems that the data encapsulation process primarily focuses on the coin staking of prime SPs. The SPs disclosed in the application are those with whom the client had communicated and cooperated at the time of application. However, due to the pledged coins and other uncontrollable factors, some of these SPs could not be encapsulated in a timely manner. In such cases, the client would contact other SPs. I have asked the client to update the information and provide the necessary explanations in the application.
![image](https://github.com/user-attachments/assets/bddb857e-9f19-45d3-a7b0-82aa6ae108a3)
![image](https://github.com/user-attachments/assets/a8467d29-042f-4e35-b470-ab1dd6a435ff)
![image](https://github.com/user-attachments/assets/476f5de9-f051-4cd0-b2fa-58967db7de6f)

As with these screenshots, I'll be reminding clients that they need to keep their GitHub comments up to date if the SP changes.
![image](https://github.com/user-attachments/assets/76e5574b-1e7d-4e5e-9155-4b1b08c46fe1)

**Comment by Marshall-btc** [comment]
3. Some information was not completed in the client's application.
As you stated, some information is missing from the client's DataCap application. However, as an Allocator, I believe I have the authority to ask additional questions. As illustrated in the attached screenshot, I also pose queries to clients regarding data preparation in the comments section.
![image](https://github.com/user-attachments/assets/ab994cb5-5c11-42bc-bfc3-9dc3c424fd9e)

In addition, I believe that Marshall Allocator has some promising aspects. Upon application, I request KYC/KYB verification from each client. They subsequently provide the requisite supporting documents, which I can also forward to the Fil+ Gov team if needed. Please find below some KYC/KYB screenshots.
![image](https://github.com/user-attachments/assets/6c805dc5-4057-4ebe-b3ee-31a63b96237f)
![image](https://github.com/user-attachments/assets/bea71abf-6991-434c-ad42-008222053ba3)
![image](https://github.com/user-attachments/assets/7515bbc7-bf9a-4dbb-a6a2-30e1577bf992)

**Comment by Marshall-btc** [comment]
I attended today's FIL+ governance meeting and will continue to run allocator in compliance with the official rules and look forward to getting official 10PiB support! @galen-mcandrew @Kevin-FF-USA Thank you very much ！

**Comment by galen-mcandrew** [comment]
Given the above information and additional investigation, this allocator is working to perform diligence and intervene with their clients to enforce compliance. We want to call attention to some specific issues that should be addressed with existing and new clients going forward, specifically:

- VPN usage appears relatively high, with little to no KYB and diligence, despite [allocator requirements](https://github.com/filecoin-project/notary-governance/issues/1057) " the client as well as the SP must provide me with descriptive information about the use of the VPN and clearly state the geographic location of the SP"
- SP distribution is mixed and not in strict compliance, especially given the above flag about VPN usage, such as https://check.allocator.tech/report/Marshall-btc/Marshall-Fil-Data-Pathway/issues/5/1724751659853.md
- clients need to accurately and completely fill out the initial application (multiple "No Response" sections)
- mixed retrieval results, but seeing some improvements

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded. 

Despite the flags above, we are seeing evidence of allocator diligence and interventions. We are requesting an **additional 5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

Please verify that you will instruct, support, and require your clients to work with retrievable storage providers. @Marshall-btc can you verify that you will enforce retrieval requirements, such as through Spark?

**Comment by Marshall-btc** [comment]
Thank you for your reply @galen-mcandrew . I will pay more attention to Allocator compliance such as Spark retrieval, KYC/KYB audit process. Improve communication with clients. Regarding the VPN issue, I will have another communication with the client. Anyway thanks a lot and let's work together in the future.

**Comment by Kevin-FF-USA** [comment]
DataCap refreshed: https://filecoinpulse.pages.dev/allocator/f03012911/#pageparamsallocator_id
Closing Issue
