### ISSUE TITLE
Community Review of QC Data Center Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#140]
Latest Compliance Report: https://compliance.allocator.tech/report/f03014608/1724113222/report.md

https://github.com/luhong123/QC-Data-center/issues/3

One client over 4 allocations 

KYC exists

Retrievals look good for SP and distribution looks good

There is no detail on data preparation, all questions in the applications are left blank and answers from client in comments are vague. I'd challenge the allocator to push for more details and demonstrate proof of how dataset is prepared and documented and how the client can actually retrieve the open files.

**Comment by luhong123** [comment]
This is the method or tool they use to prepare the data
https://github.com/luhong123/QC-Data-center/issues/3#issuecomment-2227845301
![image](https://github.com/user-attachments/assets/d1ce0d3a-de3d-4146-93e5-74d2e192e999)

**Comment by luhong123** [comment]
Here's some pre-trigger questions
https://github.com/luhong123/QC-Data-center/issues/3#issuecomment-2237990309
![image](https://github.com/user-attachments/assets/59e2ba08-a95e-4e8f-8ed0-af63e25ad9ce)

After seeing that spark retrieval is supported, I will manually fetch the data to verify that
The method used is as follows
Using the client's wallet, look up a random deal id
![image](https://github.com/user-attachments/assets/2fb94da6-f32e-43b9-891a-bf0ec4557634)
`lotus state get-deal 88223805
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqmydui7nxqovgaodc2bizhkmnzndtkmnvd7sjxjbqyfct5ngoh2fa"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f03155630",
    "Provider": "f03166668",
    "Label": "bafybeihvng7qrwaegy6yzx3kr5c6wpbzxs3kcj7tdcejspzo2c4qviu7de",
    "StartEpoch": 4173526,
    "EndEpoch": 5699926,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "6320280705102388",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorNumber": 4615,
    "SectorStartEpoch": 4154137,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1
  }
}

and than 
`lotus client  retrieve --miner f03166668 bafybeihvng7qrwaegy6yzx3kr5c6wpbzxs3kcj7tdcejspzo2c4qviu7de  /tmp/QC/`

The data will appear in /tmp/QC/ after the fetch, and then the comparison is performed

By the way, lotus no longer has the client command in version 1.28.2.   Still exists in 1.26.2

**Comment by galen-mcandrew** [comment]
Flagging something for allocator to follow-up on with their client: In their first [application](https://github.com/luhong123/QC-Data-center/issues/3) they claim to be the dataset owner, however in a subsequent [application](https://github.com/zcfil/ZCFIL/issues/3) to a different allocator they claim to be a data preparer. This may be accurate, owning one set of data and having official authorization to represent the company (https://www.yimiaohb.net/), while also acting as a data preparer for another publicly available dataset.

Additionally, while there is some [SP distribution](https://check.allocator.tech/report/luhong123/QC-Data-center/issues/3/1722930810001.md), the ISPs in US appear to be VPNs, which could mean distribution limited to HK and CN. The allocator application states "require customers to provide the real address of sp and related materials" ([question 28](https://github.com/filecoin-project/notary-governance/issues/1071#issuecomment-1902740577
)). 

@luhong123 You should direct these additional questions to your client. As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

**Please verify that you will instruct, support, and require your clients to work with retrievable storage providers.** Please reply here with acknowledgement and any additional details for our review.

Given the diligence evidence and retrieval we are seeing, we are requesting an **additional 5 PiB of DataCap from RKH** to support this allocator increasing their diligence and alignment.

**Comment by luhong123** [comment]
@galen-mcandrew Thank you for pointing this out and I will follow up!

>Additionally, while there is some [SP distribution](https://check.allocator.tech/report/luhong123/QC-Data-center/issues/3/1722930810001.md), the ISPs in US appear to be VPNs, which could mean distribution limited to HK and CN. The allocator application states "require customers to provide the real address of sp and related materials" (https://github.com/filecoin-project/notary-governance/issues/1071#issuecomment-1902740577).

I've noticed this, too.So also the geo-location confirmation for the SP in the US group, and they sent a utility bill for me to confirm, and [here's my comment at the time](https://github.com/luhong123/QC-Data-center/issues/3#issuecomment-2227861695)

Because this is the customer's private documents, can not be published here, if necessary, you can leave your e-mail, I will send later!

![image](https://github.com/user-attachments/assets/11eeab2b-7528-47b8-aa48-86c980622d12)

**Comment by Kevin-FF-USA** [comment]
DataCap refreshed: https://filecoinpulse.pages.dev/allocator/f03014608/#pageparamsallocator_id
closing Issue
