### ISSUE TITLE
2nd Community Review of NonEntropy Allocator

### ISSUE THREAD

**Issue by joshua-ne** [filecoin-project/Allocator-Governance#148]
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1022
First Community Diligence: https://github.com/filecoin-project/Allocator-Governance/issues/63

Since last community diligence and we got a refresh of 5 PiB Datacap, the following are the updates:
1. We have served two more clients: https://github.com/joshua-ne/FIL_DC_Allocator_1022/issues/23 and https://github.com/joshua-ne/FIL_DC_Allocator_1022/issues/29
2. We continue to manage the Clients' application and approval process in accordance with the guidelines of DataCap governance. We always start with small amount, building trust by checking data distribution and SP retrieval rate. 
3. Our Clients allocate DataCapto different SPs in reasonable proportions and ensure that SPs do not store duplicate CIDs.
4. Since last refreshment, we have spend quite some effort and helped SP's who did not support SPARK retrieval to behave good on SPARK retrieval tests. And now, most of the SP's our clients work with are showing good retrieval rate on SPARK. As can be checked here: https://compliance.allocator.tech/report/f03018029/1724804225/report.md

Meanwhile, we are working very actively to help the community by working on new tools for retrieval tests, which we think can work in parallel with SPARK and serve as an important complement: https://github.com/joshua-ne/FIL_DC_Allocator_1022/issues/22
1. We have established public API through which anyone can check the deal data-cids between any client and SP, which can be a good startpoint for those who also want to build novel retrieval tools
2. We have developed and just open-sourced our retrieval bot which can be integrated to github issues. Details can be accessed from the code repo. https://github.com/joshua-ne/fil-retrieval-bot. 

With update above, we would welcome the community to review our diligence and proceed to a refreshment. Thanks!

**Comment by joshua-ne** [comment]
@Kevin-FF-USA  Hi Kevin, this is our 2nd community diligence, please help us get into the review process and let me know if there are any more we can do to accelerate this process. Thank you!

**Comment by filecoin-watchdog** [comment]
[Allocator Compliance Report](https://compliance.allocator.tech/report/f03018029/1726185702/report.md )

[Example 1](https://github.com/joshua-ne/FIL_DC_Allocator_1022/issues/23)
public, open dataset
The client applied as a Data Preparer, but the application lacks answers on data preparation and the Client’s location. The allocator didn’t follow up on those answers. 

SPs provided match SPs used for deals. The client didn't use all of them, but all they used matched the list.


[Example 2](https://github.com/joshua-ne/FIL_DC_Allocator_1022/issues/29)
A compliance CID report is not available for this client. Allocator checks the retrieval rate through their retrieval bot. Based on the information generated with that bot, the client uses 5 out of 10 SPs listed, all matching the original list. 


In the allocator application, the allocator declared the DC allocation strategy to be (50TiB -> 100TiB -> 500TiB -> 1000TiB), while it seems the first allocation is 256TiB

**Comment by joshua-ne** [comment]
Hi thank you very much for your review and here is our response to your questions of concerns:

**Comment by joshua-ne** [comment]
Hi thank you very much for your review and here is our response to your questions:

1. For the first application, in terms of the missing questions, for some of them, we thought they could be ignored as they are not mandatory in the application form, and for some of them we knew the answer from communication with them and thus did not pay too much attention on them. We did make sure though, that all the important questions are fully answered by the clients. And in our following work, we will follow your feedback and make sure that every related question shall be fully answered by clients. 

2. For the SP list issue, I think this is perfectly fine and normal to have 'not-used' SPs on the list. According to our clients, it is not super easy for them to find collaborating SPs that always follow the rules, and the sealing plans of SPs change all the time. So it is kind of encouraged for clients to look for and register more SPs as planBs. 

3. In terms of the amount of the first allocation to be 256TiB instead of restricting to 50TiB, we believe that as always, we strictly follow the rule of building trust, though the initial 'trust amount' can be flexibly adjusted, as sometimes 50TiB may not be a perfect fit for all situations. And we use 256TiB as an upper bound cap for our 'initial trust amount' and I hope this flexibility can be accepted community and governance team. If not, we will remove such flexibility. Thank you! 



Thank you again for your review and please let us know if you have any further concerns or questions.

**Comment by galen-mcandrew** [comment]
From your allocator [application](https://github.com/filecoin-project/notary-governance/issues/1022#issuecomment-1890589590):

> 30. Allocation Tranche Schedule to clients::
• First: 50 TB
• Second: 100 TB
• Third: 500 TB
• Fourth: 1000 TB
• Max per client overall: 5000 TB

> 31. Will you use programmatic or software based allocations?:
Yes, standardized and software based

This is pretty explicit and does not refer to any "flexibility' based on individual client basis. Given the wording of your application, I do not see an explanation for how you would make such a determination. I advise you to follow the stated parameters of your application, including collecting all details from clients and adhering to your allocation schedule.

Despite the above, we are seeing data distribution and some retrieval for the above clients. We also look forward to seeing some additional dev's and allocator teams to review the retrieval tooling you are open-sourcing. 

Given the diligence evidence and retrieval we are seeing, we are requesting an **additional 10 PiB of DataCap from RKH** to support this allocator increasing their compliance and alignment.

**Comment by joshua-ne** [comment]
@galen-mcandrew Thank you very much for your advice and support! In our following work, we will follow the stated parameters in our allocator application and collect all information.

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03018029
