### ISSUE TITLE
2nd Community Diligence Review of ByteBase (Destore) Allocator

### ISSUE THREAD

**Issue by Destore2023** [filecoin-project/Allocator-Governance#151]
This ronud we have allocated to four clients.
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/6
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/8
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/13
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/16

These clients are currently in process. Before allocation, we did due diligence on them - using a self-designed questionnaire to collect clients' information.
![1](https://github.com/user-attachments/assets/db2cff99-1fd3-42bb-aac0-b63b4034a3b7)
![2](https://github.com/user-attachments/assets/e73e75d6-2d9f-4a42-977a-9cbbe17f298a)
![3](https://github.com/user-attachments/assets/a9ac14da-d3d9-4a1e-93a7-621f60995906)

We ask our clients to provide the latest SP list regularly as a way to verify whether the SP supports retrieval or not. Current clients are actively cooperating with it. Please refer below links for detail.
1. SP list
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/6#issuecomment-2285882967
Retrieval 
https://[check.allocator.tech/report/Destore2023/MetaPathways-Bookkeeping/issues/6/1725274025457.md](https://check.allocator.tech/report/Destore2023/MetaPathways-Bookkeeping/issues/6/1725274025457.md)

2. SP list
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/8#issuecomment-2285836575
Retrieval
https://[check.allocator.tech/report/Destore2023/MetaPathways-Bookkeeping/issues/8/1725274026727.md](https://check.allocator.tech/report/Destore2023/MetaPathways-Bookkeeping/issues/8/1725274026727.md)

3.SP list
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/16#issuecomment-2325544769
Retrieval (no report)
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/16#issuecomment-2324411176
![1](https://github.com/user-attachments/assets/dab2980f-c3be-4fef-9171-f3a0532d8c7d)

We will stop working with clients who do not meet our standards. We required our clients to distribute data to at least four SPs.
https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/13

We will keep our process up-to-date and provide feedback on github repo. We will make our work more detailed and better. Hope to get a new round of 10P DataCap for further work.

**Comment by filecoin-watchdog** [comment]
[Allocator compliance Report](https://compliance.allocator.tech/report/f03019261/1726704088/report.md)
[First review](https://github.com/filecoin-project/Allocator-Governance/issues/62)
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1039)
2nd allocation date: 2024/08/07

[Example 1](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/8)
Even though 4/9 SPs have a high retrieval rate, 5/9 has 0 or below 75%. Has the Allocator contacted their client to explain the low retrievability for those SPs?

The majority of SPs are located in the same region. 

SPs declared in the application:
f01841131 HONGKONG
f02244750 LONDON
f01807908 MADRID
f01879772 HONGKONG
f02363999 SINGAPORE

The client has updated their SPs after the first two allocations to be:
f03089385 New York
f03090976 Virginia
f03089826 Virginia
f03106356 Virginia

No explanation was made on the GitHub issue. Has the allocator made sure it was a legitimate change?

[Example 2](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/13)
The client said they wanted 1PiB of data. According to the Allocator application, they would send the first tranche at 25% of the total DC. Why is the Allocator granted 1PiB in the first and only tranche?

[Example 3](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/16)
The client has declared that there will be 10 data replicas. Is it clear why so many replicas are needed?
No CID checker is possible to generate for this client. How will the Allocator make sure the retrieval rate is on an acceptable level?

**Comment by Destore2023** [comment]
Hello @filecoin-watchdog, thanks for the review.

[Example1](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/8)

https://grafana.filstation.app/d/fea90509-20e8-4d49-b4ad-f0436da9c75d/spark-public-dashboard?orgId=1&from=now-6h&to=now&viewPanel=10

Here's their latest retrieval report on spark.

I have asked the client about their problems of retrieval. They said that some nodes (such as f03089385) have broken down and they would not continue chooes them any more. I understand the client's motive to change the sp, because I've reminded clients to replace sp that do not meet the require.

[Example2](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/13)
We had a face to face meeting with this client. 
At the time we thought the client was more truthful and qualified for storage, so we allocated 1p datacap to the client as an experiment in this round.
In the following sealing, we found that there were some problems from the client's cid report. 
Although the client made corrections later, we will not work with him again.

[Example3](https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/16)

https://check.allocator.tech/report/Destore2023/MetaPathways-Bookkeeping/issues/16/1727346611052.md

Here's their cid checker report.

We thought 10 replicas met the goal of distributed storage, and our standard is that clients need to store at least 5 or more replicas.

With an ongoing commitment to building a high-quality allocator pathway, we will build on our experience from each round of allocation practices to make our work more reflective of serving the community. As we hope that the help we provide to our clients enables more valuable data to be stored safely around the world. Also decentralized storage can be realized to develope!

**Comment by galen-mcandrew** [comment]
Overall strong diligence from this pathway. We would like to see some increased focus on the following areas:

- Verifying public client application details in GitHub, and providing diligence evidence for future bookkeeping investigations
- SP lists before and after allocations, with explanations from clients when there are changes made
- Increased investigation into SP regions and distribution, especially when VPNs are utilized
- Continuing to improve retrieval rates

Given the diligence evidence and retrieval we are seeing, we are requesting an **additional 10 PiB of DataCap from RKH** to support this allocator increasing their compliance and alignment.

**Comment by Destore2023** [comment]
Thanks Galen,

> Overall strong diligence from this pathway. We would like to see some increased focus on the following areas:
> 
> * Verifying public client application details in GitHub, and providing diligence evidence for future bookkeeping investigations
> * SP lists before and after allocations, with explanations from clients when there are changes made
> * Increased investigation into SP regions and distribution, especially when VPNs are utilized
> * Continuing to improve retrieval rates
> 
> Given the diligence evidence and retrieval we are seeing, we are requesting an **additional 10 PiB of DataCap from RKH** to support this allocator increasing their compliance and alignment.

Thank you @galen-mcandrew for your recognition and support. I will continue to work to serve our community

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03019261
