### ISSUE TITLE
Community Review of CloudX Lab Allocator

### ISSUE THREAD

**Issue by CloudX-Lab** [filecoin-project/Allocator-Governance#152]
Latest Allocator Report: https://compliance.allocator.tech/report/f03019835/1725323234/report.md

2 clients receiving allocations over several rounds.
https://github.com/CloudX-Lab/filecion/issues/10
https://github.com/CloudX-Lab/filecion/issues/14

**KYC:** We request clients to send us an email to confirm their identity.

https://github.com/CloudX-Lab/filecion/issues/10#issuecomment-2180262704
![image](https://github.com/user-attachments/assets/b6e39389-3d68-40f1-a32e-81b691f60db4)

https://github.com/CloudX-Lab/filecion/issues/14#issuecomment-2199333805
![image](https://github.com/user-attachments/assets/7984e62f-2a1b-49c7-8fc8-cb4ddf26dd18)

**SP list:** Our clients have porvided their sps in their applications and given update to us later.

https://github.com/CloudX-Lab/filecion/issues/10#issuecomment-2298109943
![image](https://github.com/user-attachments/assets/451c36c7-96c5-4a1d-a7dd-4f3138aff5e9)

https://github.com/CloudX-Lab/filecion/issues/14#issuecomment-2326217498
![image](https://github.com/user-attachments/assets/de8e9b12-f9b5-408e-94b8-86160b088690)

**Retrieval Success Rate**

Retrieval report - https://compliance.allocator.tech/report/f03019835/1725323234/report.md

![image](https://github.com/user-attachments/assets/2d0242f7-b127-469e-b98b-f65d80835a41)

The majority of the sps are supporting the retrieval, I will urge the clients to communicate with the sps, and continue to selecte sps who support the retrieval.

We will continue to focus on the client's condition and keep communicating with the client in time, so that our allocator allocation is reasonable to help data stored in the Filecoin network and promote the development of the Fil+ project.

**Comment by CloudX-Lab** [comment]
@filecoin-watchdog

Example 1
This is just a test for trigger.

Example 2
Considering the amount of data they have in a single replica, 711 TiB, we believe that the first allocation should be increased properly. So we decided in the first round to allocate 512TiB.
Our allocators support our clients in making timely adjustments to their plans, as long as they are compliant, updating in a timely manner will help their data distribution go better.
The client spoke with sps about the problem of retrieval, and sps responded that they are upgrading the program and have resumed the retrieval gradually. Now these nodes are waiting for the spark to do retrieve.

Example 3
Since we are not very skilled in the work of signing, we signed and approved 100TiB by accident while reviewing the application. After we interviewed the client and allocated them the first round, we observed the client's process of storing data and concluded that the client was able to do a qualified data storage. That's why we didn't take back the 100 TiB.
https://check.allocator.tech/report/CloudX-Lab/filecion/issues/10/1723451507861.md
https://check.allocator.tech/report/CloudX-Lab/filecoin/issues/10/1726754527861.md
Comparing the client's reports in different time periods, it can be seen that the client is improving the distribution and the number of nodes supporting retrieval is increasing.
The client keeps giving me feedback about sp. For the current problems, they promised to deal with them after the National Day holiday and resume the retrival.

As we continue to collect the shortages of our past work and keep the good parts, we will continue to do our best to do a good job with allocator.

**Comment by galen-mcandrew** [comment]
In your allocator [application](https://github.com/filecoin-project/notary-governance/issues/1001), you claimed you would be using standardized and software-based allocations to clients. That is not the same as making individual decisions for each client, according to various and ambiguous details. In the future, you will need to adhere to your stated allocation tranche schedule.

Given the details in these reports: https://check.allocator.tech/report/CloudX-Lab/filecoin/issues/14/1727796211309.md & https://check.allocator.tech/report/CloudX-Lab/filecion/issues/10/1723451507861.md, we are seeing these issues:

- duplicate data
- low retrieval rates
- low regional distribution (only 1-2 regions)

Given this review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 2.5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

@CloudX-Lab can you verify that you will enforce program and allocator requirements?  (for example: public diligence, tranche schedules, and public scale retrievability like Spark). **Please reply here with acknowledgement.**

**Comment by CloudX-Lab** [comment]
@galen-mcandrew Yes. We will improve our work and manage the cooperation with each client carefully.

**Comment by Kevin-FF-USA** [comment]
DataCap has been partially refiled.
f2o2obeorcnu4zp6zbs6i2pxkzqppxyxommqpsefi
