### ISSUE TITLE
Upcoming Allocator Call: September 17 9am PDT // 1600 UTC -AND- 7pm PDT // 0200 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/Allocator-Governance#153]
2024 September 17 Filecoin Plus Governance call will take place at 9am PDT / 1400 UTC -and- 1900pm PDT / 0200 UTC (next day). To join the call or add the meeting to your calendar, please add the [Fil+ Shared Calendar](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D)

Projected Agenda
Allocator Issues
DataCap Refresh
Check in on Allocators - Support Questions
Tooling
FAQ
Community for Discussion

Remaining time is dedicated to open public forum
If you would like to add an item to the agenda, please request time by adding a brief description of the issue/proposal/topic in the comments of this issue. Please have your request submitted in this issue at least 48hrs before the Governance meeting to ensure it is included in agenda.

Allocator Governance Meetings are recorded and posted to [Youtube](https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx)

**Comment by MikeH1999** [comment]
I have a question that I hope can be added to the agenda
https://github.com/MikeH1999/RFfil/issues/41#issuecomment-2338067858
![image](https://github.com/user-attachments/assets/a0d25ee7-5f63-400c-910c-4630467225f4)
As shown above, the applicant applies in multiple allocator paths with the same information, is this allowed?What do we do if more than one allocator signs the application?

**Comment by MikeH1999** [comment]
Sorry for bringing this up so late.

**Comment by Kevin-FF-USA** [comment]
Hey @MikeH1999 ,
Didnt catch this question before the call.  Think its time sensitive, or okay to table for the 01OCT call in two weeks?

**Comment by MikeH1999** [comment]
Can discuss again in two weeks, thanks

**Comment by MikeH1999** [comment]
Can discuss again in two weeks, thanks

**Comment by Kevin-FF-USA** [comment]
Slides:  https://docs.google.com/presentation/d/1Z0TShqVCEYixSZf2N9uz-i7yhePn5Fs-KG79txPRIaQ/edit#slide=id.g2e352ad5f07_0_657

Recordings:   https://www.youtube.com/watch?v=kzjHlIiKFc4&feature=youtu.be&themeRefresh=1
