### ISSUE TITLE
Community Review of ZCFIL+

### ISSUE THREAD

**Issue by zcfil** [filecoin-project/Allocator-Governance#159]
Latest Compliance Report:https://compliance.allocator.tech/report/f03014659/1725840012/report.md

example 1:https://github.com/zcfil/ZCFIL/issues/3
example 2:https://github.com/zcfil/ZCFIL/issues/6

KYC exists
https://github.com/zcfil/ZCFIL/issues/6#issuecomment-2280238805

Retrievals look good for SP and distribution looks good
![image](https://github.com/user-attachments/assets/512f063c-f395-4a51-9344-d52c8a32aac4)
![image](https://github.com/user-attachments/assets/f68b2011-efd2-4b33-976d-13e725dd803c)

sp not in China have provided relevant documents to confirm geographic location
![image](https://github.com/user-attachments/assets/b90b8105-2776-4438-abe2-a65bd60bdaa6)
![image](https://github.com/user-attachments/assets/49ec35eb-874c-431a-b895-796823cd780c)

If you have any other questions, please leave a comment, thank you!

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1009)
[Compliance Report](https://compliance.allocator.tech/report/f03014659/1726790413/report.md)

[Example 1](https://github.com/zcfil/ZCFIL/issues/3)
According to the allocator application, the first tranche should be 5% DC or 50% weekly allocation, so for this client it should be 350TiB, why the decision to reduce it to 200 TiB?

Currently the retrieval rate of all SPs is around 50%, has the allocator clarified this issue with the client?

[Example 2](https://github.com/zcfil/ZCFIL/issues/6)
According to the allocator application, the first tranche should be 5% DC or 50% weekly allocation, so for this client it should be 500TiB, why the decision to reduce it to 200 TiB?

1 out of 7 SPs has retrieval rate over 75%.
1 out of 7 SPs seems to not support Spark retrieval measure. 
5 out of 7 SPs have retrieval rate around 50%. 
Has the allocator clarified this issue with the client?


note to review - the specification of the amount of the first tranche results from the analysis of the allocator's application and is not a criticism of its amount, but an indication of an inaccuracy. 

The allocator clearly documents communication with the client, generates CID reports on an ongoing basis and asks additional questions based on the generated reports.

**Comment by zcfil** [comment]
>note to review - the specification of the amount of the first tranche results from the analysis of the allocator's application and is not a criticism of its amount, but an indication of an inaccuracy.

Regarding this issue, stemming from the meeting and the practice of other notaries, I have decided that for the first round I will issue 50TiB-200TiB datacap for data validation according to the information requested by the client, which has prevented abuses.
I'll mention this before and after the trigger
![image](https://github.com/user-attachments/assets/35c5f67b-3112-4fe3-8a9a-aca80e83b8ba)
![image](https://github.com/user-attachments/assets/2f44339c-979a-4792-bf3f-f646640dfdf4)

I'm also keeping an eye on the spark channel regarding the drop in retrieval rates
Significant drop in retrieval rate due to a crash in spark's internal program
[Here's a transcript of mike's communication with them](https://filecoinproject.slack.com/archives/C07JMBUMNJ0/p1726126353150969)
![image](https://github.com/user-attachments/assets/e5f97e52-300f-48ff-9f27-c13fcfa0837c)

It is possible to view previous reports where SPs have maintained high retrieval rates until issues with spark arose that caused a significant drop in retrieval rates

**Comment by zcfil** [comment]
>1 out of 7 SPs seems to not support Spark retrieval measure.

Probably talking about this SP
![image](https://github.com/user-attachments/assets/026f8e17-cbbc-4aac-bcf3-cc4ec5b73a65)

But with the previous report, I was able to see the retrieval rate, so maybe it was caused by a glitch in SPARK?
![image](https://github.com/user-attachments/assets/1628f641-266b-4dfa-beb4-fa2d6c23e476)

**Comment by galen-mcandrew** [comment]
The compliance report and the above details are good evidence for this pathway. A quick review of the two clients that are working with this allocator reveal that there may be either duplicate datasets or duplicate clients applying to multiple allocators. 

I would encourage this allocator to review this information and request some more clarification from their clients before proceeding with subsequent allocations. Checking [this client database](https://filecoinpulse.pages.dev/clients/) and searching `FengwoExtraordinary` & `AllenInstitute` revealed a total of 7 client ID's. 

In the meantime, given the evidence of initial diligence and good deal-making, we will request an additional **5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by Kevin-FF-USA** [comment]
DataCap was refilled.
https://datacapstats.io/notaries/f03014659
