### ISSUE TITLE
Community Diligence Review of TOPPOOL Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#16]
Review of TOPPOOL Allocations from @TOPPOOL-Lee
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1046

First example:
DataCap was given to:
https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/7

Public Open Dataset - key compliance requirement: Retrievability

1st point)
Allocation schedule per allocator:
First Round: 512 TiB
Second Round: 1 PiB
Third Round: 2 PiB

Actual allocation: 500Tib, 1PiB, 2PiB - this follows the guidelines

2nd point)
SPs provided by client do not include any details of entity or location, no diligence from Allocator. 

CID Checker report: https://check.allocator.tech/report/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/7/1715514801903.md

3rd point)
Second, third, fourth allocation awarded to this client.
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability.

The Allocator showed no sign of diligence after 1st allocation and gave the 2nd, 3rd, 4th allocation of 4PiBs to the client.

**Comment by Kevin-FF-USA** [comment]
Hi @TOPPOOL-LEE

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/16.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/7fb14f5c-1078-42f4-ac24-e26929204182)

**Comment by TOPPOOL-LEE** [comment]
Hello, we participated in the meeting. As the first assignee to speak at the conference, we are negotiating with the Spark team.

**Comment by galen-mcandrew** [comment]
Based on an additional compliance review, it appears this allocator is attempting to work with public open dataset clients. 

**However, the data associated with this pathway is not currently able to be retrieved at scale, and testing for retrieval is currently noncompliant.**

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

Before we will submit a request for more DataCap to this allocator, please verify that you will **instruct, support, and require** your clients to work with retrievable storage providers.

**@TOPPOOL-LEE  can you verify that you will enforce retrievability requirements, such as through Spark?** Please reply here with acknowledgement and any additional details for our review.

**Comment by TOPPOOL-LEE** [comment]
Dear Galen,

We have communicated with the client, and the client has contacted the SP  requesting the ability to retrieve data through Spark. If they are unable to retrieve data through Spark, we will flag the SP.

We confirm that we will instruct, support, and require clients to work with retrievable sp. As the allocator, we will enforce the retrievability requirements, such as through Spark.

Going forward, we will strengthen our review of client onboarding information, closely monitoring SP disclosure and retrievability. We will require clients to first disclose the SP's location and company name, while also assisting the SP to achieve retrievability through Spark.

Please let me know if you have any other questions.

**Comment by TOPPOOL-LEE** [comment]
<img width="737" alt="WX20240611-115555@2x" src="https://github.com/filecoin-project/Allocator-Governance/assets/142089399/fc09939a-5713-498e-a812-2320a819642a">

**Comment by TOPPOOL-LEE** [comment]
Dear, clinet had contacted SP again. SP uses the Venus system. SP supports retrieval, but Venus does not support Spark, the data on Spark is not very good. SP is actively assisting Spark to solve the problem.

Currently, considering that Venus currently does not support Spark, we will not cooperate with customers and SPs using Venus.

**Comment by galen-mcandrew** [comment]
Thank you, would be great to see if there is another retrieval testing tool that the community could release that works with Venus.
