### ISSUE TITLE
2nd Community Diligence Review of Hash Big Data

### ISSUE THREAD

**Issue by hash889900** [filecoin-project/Allocator-Governance#174]
Latest Compliance Report: https://compliance.allocator.tech/report/f03014732/1727222529/report.md
Previous Compliance Review Comments: https://github.com/filecoin-project/Allocator-Governance/issues/99

Datacap continues to be assigned to two existing clients

https://github.com/hash889900/HashTeam/issues/3

https://github.com/hash889900/HashTeam/issues/8

Generates CID reports on an ongoing basis and asks additional questions based on the generated reports.

I found that the retrieval rate plummeted a few days ago, and when I asked why, the customers answered that the problem was caused by a program failure on SPARK's side.
https://github.com/hash889900/HashTeam/issues/8#issuecomment-2364960456
https://github.com/hash889900/HashTeam/issues/3#issuecomment-2364959637

Based on a few days of follow-up, retrieval rates are now continuing to rise

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1050)
[First Review](https://github.com/filecoin-project/Allocator-Governance/issues/99)
[Compliance Report](https://compliance.allocator.tech/report/f03014732/1727654528/report.md)
2nd allocation - 17.09

[Issue 3](https://github.com/hash889900/HashTeam/issues/3)
The client used all the DC requested in the original application and then requested an increase in DC and the number of replicas. The client added 6 new SPs to the application.

The retrieval rate could be better, as all 11 SPs hover between 50-75%.

Below SPs might be using a VPN:
F02866666 Tokyo (actual location: Shenzhen, China, IP: 113.96.22.203)
F02588263 Hong Kong (actual location: Shenzhen, China, IP: 113.96.22.204)


[Issue 8](https://github.com/hash889900/HashTeam/issues/8)
The client has updated the SP list several times and changed the declared number of replicas.

The retrieval rate is very uneven across 12 SPs, oscillating from 0 to 72%. The allocator should ask the client about this inconsistency.


In general, the allocator ensures that the data clients provide is correct. They ask questions when detect discrepancies and regularly check CID reports, highlighting when the retrieval rate is too low.

**Comment by hash889900** [comment]
Thank you for pointing this out, I will continue to follow up on this issue, thank you!

**Comment by galen-mcandrew** [comment]
Based on the investigation and details provided, we are seeing mixed compliance results. Some areas for this allocator to focus on should include:

- Clients changing replicas/project sizes without sufficient justification. For example, would it be better for a client to open a new application for these new SPs and replicas?
- SPs utilizing VPNs without increased diligence
- Highly variable retrieval rates
- Data preparation details from clients

Given this review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application, with some extra focus on these areas. If so, we will request an **additional 10PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by hash889900** [comment]
Follow up on the issues you mentioned, thanks for reviewing!

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03014732
