### ISSUE TITLE
Community Review of TopBlocks

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/Allocator-Governance#177]
Latest Compliance Report:https://compliance.allocator.tech/report/f03019931/1727395347/report.md

example 1:https://github.com/filplus-bookkeeping/TopBlocks/issues/10

Retrievals and data distribution data look good
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/bb199665-e438-40b9-9433-694afd171c17">

If you have any other questions, please leave a comment, thank you!

**Comment by woshidama323** [comment]
Thanks for your review 

> [Examle 1](https://github.com/filplus-bookkeeping/TopBlocks/issues/7)
> The dataset this client proposes seems to be already stored on filecoin: [github search results](https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+mouse+brain&type=issues)
> The allocator should’ve asked why the client wanted to store another replica.
> After no response from the client, the allocator decided to close the issue.

You can see that all the datasets have expired on filecoin,  and also as I know, they have not been restored at the moment
So, from my point of view, I think this is fair.

>> **After no response from the client, the allocator decided to close the issue.**
Since there is no response from the client at Slack, GitHub. etc, We need to move on instead of waiting again and again
you can see we also left enough time for client handling but still no response. 

> [Example 2](https://github.com/filplus-bookkeeping/TopBlocks/issues/10)
> This client seems to have data similar to the client in Example 1. It also covers Allen Institute files. This leads to a similar conclusion that this data was already stored on the filecoin system.

Same as Example 1 


> 4 out of 14 SPs have a retrieval rate of 0%, other 10 operate between 49-92%.
![image](https://github.com/user-attachments/assets/13740185-d931-4412-80cf-7564c70d0766)
They've taken action for that, Some boost deploying issues blocked them, 


As for CID sharing, I have asked them for reasons. 
![image](https://github.com/user-attachments/assets/f56596f6-52f7-4d00-afda-0f77eca17530)

and you can see that the amount of datacap is very small. So I think they can continue onboarding
![image](https://github.com/user-attachments/assets/6aee941c-40a5-46e7-90db-54763f9542c5)


The path of onboarding is not always smooth, but we are doing our utmost to complete the tasks. We look forward to your response.

**Comment by galen-mcandrew** [comment]
According the [compliance report](https://compliance.allocator.tech/report/f03019931/1728954689/report.md), this team has primarily worked with only one client (4.87PiB). As noted, checking [this client database](https://filecoinpulse.pages.dev/clients/) and searching `AllenInstitute` reveals some duplicates on the network. I would love some more details or evidence of the investigation that showed these other datasets as `expired`. Can you show the dashboard, explorer, or tools you used to determine those other clients were not active? Development of tools and process for that investigation could help other allocators and data-prep teams to quickly determine if a dataset is redundant.

Overall we see evidence of mixed compliance, with the allocator investigating and intervening with clients, but most of this allocator's history is with that sole client. Going forwards, we hope that the allocator continues to intervene quickly and build trust over time with clients. We will request an additional **5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03019931
