### ISSUE TITLE
3rd Community Diligence Review of  IPFSTT

### ISSUE THREAD

**Issue by nicelove666** [filecoin-project/Allocator-Governance#187]
Allocation review of IPFSTT allocator application: filecoin-project/notary-governance#1006
First round of due diligence: 9
Second round of due diligence: 93
Compliance report: https://compliance.allocator.tech/report/f03011612/1728951855/report.md

20P allocation report, 9 clients and 50 SPs have been cooperated, and the number of clients is still increasing.

**Enterprise client**

1. DataCap was provided to: nicelove666/Allocator-Pathway-IPFSTT#58(0PiB)

We are actively looking for high-quality enterprise clients, but the enterprise client applied for DC multiple times during v4 and applied to fidlabs twice during v5. Willscott of PL had closed the application. Therefore, we rejected the client and gave the specific reasons on github.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/58#issuecomment-2362849127

2. DataCap was provided to: nicelove666/Allocator-Pathway-IPFSTT#49(4.75PiB)

The client proved its identity through domain name email (we sent the email to filplus-app-review@fil.org).
The client has newly cooperated with two US SPs to increase regional diversity (explained in advance on GitHub). The new SP needs time to build the index. Only after the index is built can the retrieval success rate be seen on Spark. Therefore, we suspended signing for them for about 5 days. After all SPs support Spark, we signed next round for the client.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/49#issuecomment-2397246285

3.DataCap was provided to:
nicelove666/Allocator-Pathway-IPFSTT#34 (3.5PiB, 3P approved in the first round of 10P, 0.5P approved in the second round of 20P)

This is our first enterprise client, recommended by NonEntropy. The NonEntropy team completed the update and upgrade more than a month ago, and all SPs support spark. We approved a total of 3.5PiB for this client. 3P was approved in the first round of 10P, and 0.5P was approved in the second round of 20P. After the last round of 0.5P was signed, the SP they cooperated with mixed the two hard disks data and appear a little CID. Then, we refused to continue to help them.
This is the only one of our clients that has a CID.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/34#issuecomment-2363176579

4. DataCap was provided to:nicelove666/Allocator-Pathway-IPFSTT#74 (1.75PiB)

The client verified its identity through a domain email (we sent the email to filplus-app-review@fil.org); all SPs of this client support spark, so we signed the first round of 256TiB for them.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/74#issuecomment-2399394763

The SP disclosed by the customer is the same as the SP actually cooperated with, and the spark support rate is high. I support them and hope they can increase it from 60% to 75%.

**Public dataset client**

5. DataCap was provided to: nicelove666/Allocator-Pathway-IPFSTT#41(3.75PiB）

The client had a problem with duplicate data. fidlabs/allocator-tooling#73 shows that duplicate data is a bug, which has been fixed now, and the bot shows the data normally.
Considering that the gap between the SP disclosed by the client and the actual SP of cooperation is quite large, we did not help them sign the next round for the time being.
However, the client contacted us many times, hoping that we would continue to sign for them. Regarding the situation of this client, our team had different views. Therefore, we sent an email to the governance team on September 28, hoping to get the establishment and opinions of the governance team.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/41#issuecomment-2373799806 https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/41#issuecomment-2398495225
![WechatIMG1863](https://github.com/user-attachments/assets/bbe59f10-298d-49b0-85cf-be609af69a1e)

6.DataCap was provided to: nicelove666/Allocator-Pathway-IPFSTT#51（1.75PiB）

After signing the first round of 256T, the client contacted us several times to sign the second round (starting from September 8), but duplicate data (bug) appeared, so we did not continue to sign.
Like #41client, our team disagreed on whether to sign for the client, and we contacted the governance team by email.
Later, the governance team solved the duplicate data bug, checkbot showed that the data was normal, and the duplicate data disappeared.
We signed 512T for them on October 6. If the next round of spark data is improved, we will continue to sign.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/51#issuecomment-2394967058

7.DataCap is provided to: nicelove666/Allocator-Pathway-IPFSTT#53（1.75PiB)

All SPs support Spark, the average retrieval rate is greater than 50%, and the disclosed SPs are the same as the actual cooperative SPs.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/53#issuecomment-2399590259

8.DataCap is provided to: nicelove666/Allocator-Pathway-IPFSTT#65(1.75PiB）

The disclosed SPs are the same as the actual cooperative SPs. After the first round was used up, the bot showed that there were two SPs that did not support Spark, so the second round was not signed. Until all SPs support Spark, we signed the second round of 512T.Now,We have observed that the retrieval data is constantly improving.
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/65#issuecomment-2390534091
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/65#issuecomment-2397184738

9. DataCap provided to:
nicelove666/Allocator-Pathway-IPFSTT#72
The first round of 256TiB has been approved, The bot shows that a SP does not support retrieval, so we will not support them until all SPs support spark.

**Comment by filecoin-watchdog** [comment]
Out of the 20 PiB you received after the previous review, you still have about 9 PiB to allocate. Why you're requesting a review so early?
The review will be performed once you have used 75% of the DC from the previous allocation.

**Comment by nicelove666** [comment]
Dear governance team @filecoin-watchdog , I am glad to see your reply.
Here are some updates: We signed 512T+1P=1.5PiB for #74. 7.25PiB is left.
#65 is urging us to sign 1PiB. However, their spark retrieval is relatively low, we may only sign 512TiB for them. Considering that the remaining quota is too small, we may directly reject this customer until the quota is updated.
In the next two days, we need to sign 1.25PiB for #49. #51 signs 1PiB. #72 signs 512TiB. In the next week, more needs to be signed.
Considering the repeated urging of #41, if the governance team confirms that #41 can sign by replying to the email, then we may need to sign 1PiB or 512TiB for #41 to verify whether #41 can fully comply.

You can see that we have added a new application for #76.
At the same time, an enterprise client and more clients with public data contacted us, hoping to store data on the Filecoin network.

We have 13 ongoing clients that need DC approval. Our DC can no longer cover the existing 13 clients. Therefore, our team decided that we will not review new clients until the governance team approves the next round for us.

Considering that the number of clients and SPs for this round of 20P is increasing, this may increase the workload of the governance team and need you to spend more time on review. Our team believes that disclosing our situation in advance may help reduce your workload and save your time.

If you have any questions please let me know, Thanks for your hard work.

**Comment by nicelove666** [comment]
To be fair, we signed 1PiB for 49, 51, and 65. The SPs of these three clients are completely different. 74 modified the application, changing the total amount from 2PiB to 3PiB. We will not approve their request until the new quota is released.

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/Allocator-Governance/issues/182

**Comment by nicelove666** [comment]
Dear@filecoin-watchdog , thanks for your reply, you have raised three core issues:

1、More DCs are granted to new clients than to existing clients.
2、Some datasets submitted by clients have been applied for with other allocators and have storage records on the Filecoin network.
3、The Spark retrieval rate of some SPs is relatively low.

Here are our responses:

1、We are committed to decentralizing DCs and helping more clients and SPs. Therefore, we have cooperated with a vast number of clients, and our SPs are scattered across the globe. The proportions of the top three SPs are: 5.13%, 4.04%, and 3.79%. If we were to favor existing clients, we wouldn't be able to assist as many new clients, and the proportion of DCs obtained by SPs would be high, leading to centralization of DCs.
Of course, considering your suggestion, we will focus on assisting existing clients in the next round, and we will strive to increase their proportion to 50% or even more .

2、We strongly agree with the viewpoint that the Filecoin network does not need duplicate data backups. you can see that the IPFSTT allocator does not have duplicate datasets. When clients apply with public data, such as USGS, we will reject their applications because other clients have already applied with USGS to us. When clients apply with enterprise data, such as K12 International (#58), although K12 International is not stored on IPFSTT, we will check on https://allocator.tech/ and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues (where V3 and V4 applications are submitted). Why are there these differences? enterprise data is smaller,  when enterprise clients apply to us, we need to confirm that they are new to the Filecoin network. Public datasets contain a vast amount of data, for example, EMPIAR (https://www.ebi.ac.uk/empiar/) has 4.83P of data on its network, and if five backups , 24P can be applied for. Although multiple individuals have applied for the EMPIAR dataset with multiple allocators, if EMPIAR does not exist under the IPFSTT allocator, our team may approve it, depending on the quantity of the dataset and the number of DCs obtained.
Of course, considering your suggestion, our team will support entirely new datasets (both for enterprise clients and public data), although this is challenging. We will require clients to do, and if clients need assistance, we will help them find such datasets.

3、We are sure that all SPs cooperating with our clients support retrieval. When selecting clients, we focus on whether their technical solutions support Spark, for example, we will directly reject clients using DDO. At the same time, we are also very concerned about whether SPs are willing to keep CAR files for a long time. If SPs want to save costs and are unwilling to keep CAR files, we will not cooperate with them. The fluctuation in retrieval rates that you mentioned is related to many factors, such as the network, equipment, and client technology. Our team is actively helping clients solve these problems. If there are issues that our team cannot resolve, we will submit issues or contact Willscout on Slack. Here, Let us express our gratitude for their hard work.@willscott
Of course, we will continue to require and assist clients in improving their Spark retrieval rates.

**Comment by nicelove666** [comment]
Example 1
Considering that governance Team need to review, we have kept them open. We hope that all cilents who have used DC, whether compliant or not, remain open,  a distribution record for IPFSTT. Now, this cilent has been closed by us.

 Example 2
Regarding cilent2, our team has held multiple meetings for discussion, but no consensus has been reached. Therefore, we have contacted the governance team via email, hoping to get the advice. now, we think that perhaps we should give them another chance, so we can observe their progress. we had support for them with 1PiB.

 Example 3
The Allen Institute requested a relatively small dataset, 2PiB ( many cilents request 5P-10P). Considering their stable and high Spark support rate, and that the disclosed SP matches the actual cooperating SP, we approved their request.

 Example 4
In the first round, with 256TiB, they only cooperated with 3 SPs, but they promised to increase the number of SPs in the second round. We just contacted them,  confirmed that they have increased the number of SPs. According to FIL+ rules, cooperating with 3 SPs in the first round is compliant. as a new cilent, we will keep a close eye . Thanks for your reminder.

 Example 5
This is an enterprise cilent and we are very concerned about the situation of enterprise cilents.
Firstly, on https://allocator.tech/, we can only see the application on IPFSTT. Thank you for pointing out that the cilent has also applied on ND. We carefully compared the application times; their application time with us was [specific date], and their application time on ND was [specific date]. Moreover, ND has not approved their request. If ND approves their request, we will reject them.

 Example 7
Regarding the technical plan and data preparation, we mainly confirm these details through phone calls and WhatsApp. Since most  cilents are not fully proficient in data downloading and distribution, phone calls let us to understand the situation more clearly and efficiently, and to answer their questions. In the next round, we will focus on inquiring about the  cilent's technical plan and synchronize it on GitHub. 

 Example 6 and 8
The datasets for cilents 6 and 8 are relatively large, but we have allocated fewer DCs to them. Thank you for your suggestion. We have informed the cilent that if they wish to continue receiving support, they should seek out new datasets.

**Comment by filecoin-watchdog** [comment]
@nicelove666 
A few comments on some points:

1. As you noted, this was just a suggestion. From a review perspective, a closed application signals that the client has been rejected. This, of course, does not mean that there is any suspicion when the application remains open.

3., 6., and 8.: The amount of data the client requests is not a factor in determining the quality of the data. A much more valuable action would be to ask what part of the data the client wants to store on filecoin and why, since the data already exists on the network. This contributes to better verification of the datasets to other allocators and clients and increases the quality of the stored data.
Some datasets are much larger than what the client requests. That is why asking what precisely the client has chosen to store is so valuable.

4. If the client uses fewer than 4 SPs, the CID report will always show an incorrect data sealing percentage. The allowable amount of data for one SP is 25%, and keeping this factor under the rules is impossible with fewer than 4 SPs.

7. it is worth noting that the action was taken. Otherwise, it looks as if it was not.

---
And in reference to the previous comment. I noted that you gave new customers more DC than existing customers, but that is a fact, not a complaint. I think the gov team may have more to say on this topic than I do.

**Comment by nicelove666** [comment]
Thank you for taking the time to continue discussing the following two questions with us:

1. In the first round, can the client use only 3 SPs? And if the client uses 3 SPs, what will the checkbot report look like? In [Case 4](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/72), this client used only 3 SPs in the first round, but the checkbot data showed no issues. According to FIL+ rules, clients in the first round can use only 3 SPs. However, in the second round and beyond, clients must use at least 4 SPs, with no single SP accounting for more than 25%. In fact, all our clients in the second round and later have collaborated with 4 or more SPs. However, moving forward, we will require all clients to have 4 SPs in the first round.

2. For a qualified allocator, is it better to have more new clients or more established clients? For a long time, we have believed that having more new clients is preferable. New clients can increase decentralization; distributing DataCap (DC) across more clients and SPs can reduce issues like "concentrated trading" and "self-trading." Logically speaking, the more clients there are and the more decentralized the SPs, the more it aligns with the decentralized nature of the Filecoin network. From a difficulty perspective, I believe that maintaining established clients is easier than finding new ones in any industry; in fact, constantly seeking new clients can be quite challenging. It is easy for us to distribute all DC to established clients, but this only leads to increased centralization. From a fairness standpoint, since the number of allocators is less than the number of clients and SPs, if allocators only distribute to established clients, it can be very discouraging for many new clients.

However, considering that you have raised the discussion about new and established clients twice, our team has carefully considered your reasoning for favoring established clients. This may be due to the lack of relevant experience from new clients that makes them seem untrustworthy, or perhaps because you are unsure whether a brand-new GitHub account represents a strong, familiar company or an unfamiliar, inexperienced individual. Your concerns are valid, but regardless of who is behind the GitHub account, we should base our decisions on the results from the bot when determining whether to continue supporting them.

Even though we believe that supporting new clients is more beneficial, we are still willing to accept your suggestion to elevate the proportion of established clients to 50% or even 80% in the next round.

If possible, we hope to delve deeper into discussions about new and established clients. We are very eager to know the governance team’s thoughts so that we can work according to their guidance in the next round. If this requires opening an issue, discussing in a conference call, or any other means, we are willing to pursue it to obtain clear guidelines from the governance team.

Finally, all the discussions have been relayed to the relevant LDN.

**Comment by nicelove666** [comment]
@Kevin-FF-USA Can you change Awaiting Response from Allocator to Diligence Audit in Process for me?

**Comment by Kevin-FF-USA** [comment]
Hi @nicelove666,
Just wanted to keep this thread updated (from our Slack DM).  This review is being finalized by Galen now.  Should see a comment from him shortly with the updated Diligence guidance.  

Appreciate you being so detailed in the communications and questions in issue.  Thank you.

**Comment by galen-mcandrew** [comment]
Thank you for the time to investigate, as you noted the larger allocations bring more time and deeper investigation. I will follow up with a longer comment addressing more of the questions raised above, such as new vs old clients. Also happy to discuss on Governance calls or at the upcoming FIL DevSummit.

Given the overall evidence, we would like to request an additional **20PiB of DataCap** at this time.

**Comment by nicelove666** [comment]
@galen-mcandrew Thanks for your patient investigation efforts.We will continue to work hard
