### ISSUE TITLE
[Allocator Application] <I am a Filecoin enthusiast and technology geek, An independent individual>< LUCKY POOL > PR #204

### ISSUE THREAD

**Issue by martapiekarska** [filecoin-project/Allocator-Governance#213]
*Allocator Application*

## Application Number
recNswtykWG9zeDxi

## Organization Name 
I am a Filecoin enthusiast and technology geek, An independent individual

## Organization On-chain Identity
f15ahraahohahm6qdf3lhiohgg3kvboztfge22o7q

## Allocator Pathway Name
LUCKY POOL 

## Github PR Number
204

## Region of Operation
Asia minus GCR,Europe,Greater China Region,North America

## GitHub ID
ssnks1

## On-chain address

I have a multisig I want to provide now

## Type of Allocator
Similar to existing allocator pathways

## Filecoin Community Agreement
_As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, allocator, or other operating entity_
Acknowledge

## Type of Allocator and RFA List
Manual - Existing similar diligence pathway

## Allocator Description
We hope to develop a market-based automated platform. Although it takes time, is not an obstacle for us.
Our difficulty is that we have not figured out what a market-based platform?
It may be similar to BDE (BDX), but their official website seems to be unavailable.
We believe that a market-based automated platform is likely to be a better version of FIL+, and it may also be the final version.
Before we figure out how to do it, we want to start with manual methods.
However, by upgrading the existing manual methods, it may become the best automated platform. Upgrade direction:
1\. As an Allocator, how can you better view the sealed data? Can the function of viewing data be integrated into the bot? If the bot can integrate this function, the bot will become very powerful and intelligent.
2\. When the bot can automatically judge the cilent's situation, the bot can decide whether to trigger the next round based on the cilent's situation. For non-compliant cilents, the bot directly refuses, and for compliant cilents, the bot directly signs. Then, a powerful automated platform can be truly formed.
3\. Therefore, we hope to become an Allocator, then we can understand the Allocator's signature tool and other systems, and then strive to find more inspiration.

## Monetization and Fee structure
Client fees,Block rewards, pools,SP fees,Client staking. 

## Target Clients
Web3 developers,Commercial/Enterprise,Open/Public 

## Client Diligence Check
3rd party Know your business (KYB) service,Client promise/attestation,Manual verification,NDA with additional verification

## Description of client diligence
Three cores:
1\. Establish a github application form and archive it permanently. We will review the needs of clients, guide valid clients that meet the rules, and distinguish the quality levels of clients
2\. Ensure the fair distribution of DC resources, do a good job of effective data management, prevent abuse, and regularly check whether the data is compliant
3\. Actively participate in FIL+ official meetings, synchronize the latest official strategies, and strictly abide by the basic principles of FIL+
Specific content:
1\. Clients fill out the github application form, which is permanently archived, and the application form is open to anyone for viewing at any time.
2\. Strictly check the authenticity of the applicant's information. If the client is a company, the business license and corporate email verification are required. If the client is an individual, the personal identity information needs to be verified. Companies and individuals are managed separately, and the individual quota cannot exceed one-tenth of the minimum company quota. When reviewing clients,
3\. We will focus on the technical solutions of clients. Clients' application forms on GitHub must be filled out, especially the technical solutions and data preparation content.
4\. We will strictly abide by the rules of FIL+ and use the data of the bot as a guide. When the bot prompts, we will ask the clients to make adjustments. We will not bring new quotas to the clients until they are compliant.
5\. We plan to manually check the sectors to determine the authenticity of the data. Although it is very troublesome to check the sectors manually, we still hope to be able to check the sectors manually for everyone.
6\. We will strictly follow the guidance of the governance team, actively participate in the meeting, and submit proposals to deal with controversial content.

## Type of data
Public, open, and retrievable

## Description of Data Diligence
1\. Clients information review: For corporate clients, collect basic information about clients, including company registration documents, business licenses, and related contracts. Confirm the source of the data and ensure that it comes from legal channels. Check whether the data complies with local and regional legal requirements.

2\. Clients information review: For public data sets, check whether authorization is required, check whether the public data set is stored multiple times on the Filecoin network, and ask clients which part of the data will be downloaded.

3\. Sampling inspection: Randomly select samples from the data sets provided by clients, and calibrate the compliance of the data from time to time to assess the overall data quality and legality. And conduct in-depth reviews of specific risk areas or important data points.

4\. Audit evidence presentation: Generate a detailed audit report, including the process, findings, and conclusions of data due diligence. Show the reviewed sample data and its compliance evidence to the governance team.

5\. Check the bot data before each round of signing. Bot will become the main guiding factor for whether we continue to support clients. We will require clients to improve their solutions and comply with regulations based on the situation of bots. We only support compliant clients.

6\. When a dispute occurs, whether it is a new Client or an existing Client, we will immediately stop the allocation of DC and form an investigation team to investigate. If necessary, we may involve the governance team in the investigation or discuss it at the Notary Committee meeting.

## Data Preparation
Singularity,Go-CAR,IPFS Kubo,Other existing ecosystem tooling

## Replicas required, verified by CID checker
5+

## Distribution required
Equal distribution of deals across regions

## Number of Storage Providers required
5+

## Retrieval Requirements
Public data highly retrievable over Spark. 

## Allocation Tranche Schedule TypeStandardized scaling tranche schedule.
150

## Will you use FIDL tooling, such as allocator.tech and other bots?
Yes, all available tools

## GitHub Bookkeeping Repo Link
https://github.com/ssnks1/Allocator-LUCKYPOOL

## Success metrics
Number of clients,Number of paid deals,Retrievability of data,Amount of data onboarded, daily & aggregate,Number of returning client customers,Ecosystem marketing/comms

## Timeline to begin allocating to clients
1 week from RKH approval

## Funnel: Expected DataCap usage over 12 months
75-100PiB

## Risk mitigation strategies
Before the Clients begin, we will conduct a detailed compliance and technical briefing to ensure that Clients fully understand the FIL+ risk rules. This process is crucial for laying a solid foundation for cooperation between both parties.

1. Timely Identification and Correction of Non-compliance
   Once we identify any Clients abusing DC, submitting invalid data, or engaging in other non-compliant behaviors, we will immediately require them to cease such actions and make improvements. If Clients refuse to make improvements, we will have no choice but to suspend their usage rights to maintain the overall compliance and security of the system.

2. Control of Clients' Quality 
   In the initial phase, we will limit the Clients' quotas, setting the first round quota at 150T. By using a smaller quota to verify the Clients' technical capabilities and compliance, we can not only reduce the likelihood of subsequent risk triggers but also help us evaluate and manage Clients more effectively.

3. Observation List Management
   Once Clients are placed on the observation list, we will no longer allocate new DC to them. During this period, we will continuously monitor the latest developments of the Clients until their data is updated and meets compliance standards. This measure aims to ensure that we can effectively monitor and respond to potential risks.

4. Seeking Governance Team Guidance 
   When we find the behavior or compliance of certain Clients, we will proactively seek guidance from the governance team. This step will ensure transparency and professionalism in decision-making, while also helping us better understand and address complex situations.

## Dispute Resolutions
We will promptly review the disputed LDN to clarify the specific content and key points of the dispute. This step is crucial, and we will pause DataCap allocation to prevent the dispute from escalating further. 

We will request the client to provide a valid explanation within a specified timeframe on GitHub. The client should explain their actions during the DataCap usage process and outline reasonable technical solutions to facilitate a quick resolution of the dispute. 

All content and progress regarding the dispute resolution will be transparently documented on GitHub. This includes the initial dispute proposal, confirmed dispute points, the client's explanation, and the outcome of the resolution process. This approach ensures that all stakeholders have access to the latest information, enhancing the transparency of the handling process.

If the dispute cannot be resolved through internal communication, we will seek support from the Fil+ governance team. This can provide a third-party impartial perspective for resolving the dispute and ensure the rationality of the decision-making process. We will handle and make decisions based on the guidance of the governance team.

## Compliance Audit Check

We will check the client's compliance from six aspects:

1. Disclosed SP vs. Actual SP: We expect the disclosed storage providers (SP) to be the same as the actual cooperating SP. If the client adds any new SPs, they must disclose this promptly.

2. Use of VPN by SP: While we understand that VPNs can help prevent hacking, we prefer that SPs do not use them. We will utilize paid services from https://seon.io/ to check whether addresses are using VPNs. If a client uses a VPN for security reasons—for example, if they have previously suffered a hack and wish to enhance security—we request that they inform us of the reasons and their actual geographic location.

3. Support for Spark: The support rate for Spark by SPs has been synced with our bot. We will use the bot to monitor the SP's support rate for Spark, and we will not accept SPs that do not support Spark. We expect SPs to have at least a 75% support rate for Spark.

4. CID Sharing and Data Duplication: We will check for issues such as CID sharing, storage of duplicate data, and unreasonable data backups through real-time data monitoring of LDN via our bot.

5. Checking LDN Balances: We will use the bot along with https://datacapstats.io/ and https://ehume.com/#/ to check LDN balances and ensure that data is allocated to four or more SPs.

6. Manual Inspection of Sector Data: We will manually check sector data to identify whether it consists of inflated data. We believe that verifying the authenticity of stored data will be a focus moving forward, and we plan to conduct a sector data check for each LDN.

## Compliance Report content presented for audit
Success metric: Proof of Payments from clients,Success metric: onchain report of data onboarded,Success metric: onchain data report,Client Diligence: Client statements, client provided verification,Client Diligence: Legal Review documents,Client Diligence: Financial Audits and Credit Check reports,Client Diligence: KYC/KYB report on clients,Data Compliance: Proof of provenance report,Data Compliance: Data Samples,Data Compliance: Manual report,Compliance: CID report,Client/Data Compliance: external third-party audit ,Contributions: Educational Materials Developed,Contributions: Github repos with the tools developed. 

## Connections to Filecoin Ecosystem
Storage provider,Big data contributor

## Slack ID
wilson

**Comment by ssnks1** [comment]
Sorry, it seems that we filled in the wrong title. It seems that we only need to fill in "LUCKYPOOL". Could you  @Kevin-FF-USA help us modify it, or we can resubmit a new one and you can help us close this old one? 
Thank you.

**Comment by ssnks1** [comment]
We rewrote 220, please help me close this @Kevin-FF-USA
