### ISSUE TITLE
Community Review of Pluskit Allocator

### ISSUE THREAD

**Issue by PluskitOfficial** [filecoin-project/Allocator-Governance#223]
Application Link: V5 Notary Allocator Application: Pluskit · Issue #1016 · filecoin-project/notary-governance · GitHub 
Collaborating Client 1: [DataCap Application] <NOAA-HRRR> · Issue #5 · PluskitOfficial/bookkeeping · GitHub 
Total DC granted: 390TiB 
Collaborating Client 2: Codoon Health · Issue #7 · PluskitOfficial/bookkeeping · GitHub 
Total DC granted: 10TiB
Collaborating Client 3: [DataCap Application] <PGC> - <ArcticDEM> · Issue #9 · PluskitOfficial/bookkeeping · GitHub
Total DC granted: 1.5PiB
This client's SPs distribution and data copy are in good condition. But initially we didn't focus on the search success rate, and we'll start focusing on it in future.
Collaborating Client 4:[DataCap Application] <CrypBell> - <End-Use Load Profiles> · Issue #11 · PluskitOfficial/bookkeeping · GitHub
Total DC granted: 512TiB
The client's SPs distribution and retrieval success rate are average. We conducted inquiries during the second round of distribution and will continue to pay attention after that.
Collaborating Client 5:[DataCap Application] <AWS> - <4D Nucleome> · Issue #13 · PluskitOfficial/bookkeeping · GitHub 
Total DC granted: TiB 
The client's SPs distribution and data copy were in good condition but the search success rate was mediocre. We conducted inquiries during the second round of distribution and will continue to pay attention after that.
Dear FIL+ Governance Team, @galen, @kevin, @filwatchdog,
After onboarding as a V5 notary, we immediately began DataCap allocation. We did most of our vetting through Github and email. Very few clients applied at the beginning. But recently, three more clients began to apply  and our DC was almost allocated.We respectfully ask for another chance, and we are committed to showing you our fast progress and diligence.

**Comment by filecoin-watchdog** [comment]
@PluskitOfficial 
[NOAA HRRR](https://github.com/PluskitOfficial/bookkeeping/issues/5)
* This dataset has been stored multiple times, making the justification of "it’s important data" less convincing. [Reference](https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+hrrr&type=issues).
* SPs list provided by the client:
f02127525 (HK)
f02234029 (HK)
f02125293 (HK)
f02094399 (CN, Guangdong)
f02061213 (CN, Heilongjiang)
f02128256 (Canada)
f02041447 (CN, Hubei)
Client stated: 
>"I will continue to cooperate with storage nodes I’ve used before and ensure no nodes exceed 20% of data storage."

* SPs used for deals:
f03100004
f03241837
f03242023
f01084941
* None of these SPs match the provided list, nor was the list updated in the issue.
* Two SPs exceeded the 20% storage limit despite the client’s commitment to avoid this.
* Only one SP achieved a retrieval rate above 75%.
* Please clarify the allocation schedule.

[ChengduCodoon Health Technology Co., Ltd](https://github.com/PluskitOfficial/bookkeeping/issues/7) 
* additional questions were asked (some technical issues were mentioned and the discussion took place here: https://github.com/PluskitOfficial/bookkeeping/issues/2). Overall a lot of things were discussed, but I feel the data preparation was not properly explained on the form and should be discussed more. 
* SPs list provided:
f03106356 US
f03090976 US
f03089826 US
f03087482 US
f03078693 US
* SPs list used for deals:
f03100004
f03231666
f03216485
* None SP matches the provided list.

[PolarGeospatial Center](https://github.com/PluskitOfficial/bookkeeping/issues/9)
* data was stored several times before [DataCap Application 1/2](https://github.com/filplus-applications/filecoin-plus-large-datasets/issues/1)
[DataCap Application 2/2](https://github.com/filplus-applications/filecoin-plus-large-datasets/issues/2). The client said they think their data are the most up to date. What they based this on? Did they check that somehow?
* the allocator said in the one of the comment:
>5.Please specify the storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.


Did I understand correctly it is about amount of data storage within one SP? If so, this is a factor that depends on the number of granted allocations, being at 20% with the final allocation. I think more explanation might be needed here.
* SPs list provided or updated:
f01975299 Guangdong
f02816097 HongKong
f03100009 Guangdong
f03233966 Zhejiang
f02828242 HongKong
* SPs list used for deals:
f01084413
f03100004
f03100009
f03231666
f03216485
f03233966
f03228358
f01975299
f02816097
f02828242
* All updated SPs match the latter list, yet 5 SPs weren’t updated on the GitHub.
* 3 SPs have very low retrieval.


[NREL](https://github.com/PluskitOfficial/bookkeeping/issues/11) 
* dataset was stored before. [Reference](https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+nrel-pds-building-stock&type=issues).
* All used SPs match the provided SPs list.
* 1 out of 4 SPs has retrieval of 0%. 


[DN Data Coordination and Integration Center](https://github.com/PluskitOfficial/bookkeeping/issues/13)
* this dataset was stored before (top 3 results) [Reference](https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+4dn-open-data-public&type=issues).
* 2 SPs don’t match the provided list. 
* 1 SP has retrieval of <1%

**Comment by PluskitOfficial** [comment]
1.[NOAA HRRR](https://github.com/PluskitOfficial/bookkeeping/issues/5)

> This dataset has been stored multiple times, making the justification of "it’s important data" less convincing. Reference.


At the time, we thought the logic of "because data is important, it needs to be stored multiple times" was sound.
Also, does the community rule not duplicate storage? If so, we will strictly inquire/check subsequent applications.

> None of these SPs match the provided list, nor was the list updated in the issue.


When clients actually stored, the SP they work with changed. We think it is a very reasonable situation, so there is no restriction on it. However, we will strengthen the check in the future.

> Two SPs exceeded the 20% storage limit despite the client’s commitment to avoid this.
> Only one SP achieved a retrieval rate above 75%.


Considering that this client was the first time to cooperate, and no major problems were found before the approval, so we made the allocation.
After the allocation, in order to better follow up the use of them, we conducted a return visit tracking, but did not receive any reply.
Therefore, we consider that this client is not a good one. If we receive a reply again in the future, we will ask these two questions.

> Please clarify the allocation schedule. 


Ok, we'll take note of that in future.
2.[ChengduCodoon Health Technology Co., Ltd](https://github.com/PluskitOfficial/bookkeeping/issues/7)

> additional questions were asked (some technical issues were mentioned and the discussion took place here: Codoon Health PluskitOfficial/bookkeeping#2).Overall a lot of things were discussed, but I feel the data preparation was not properly explained on the form and should be discussed more.


According to our practice, we will ask our clients a series of routine questions, which include a number of data related questions, such as data content, data volume, SPs’ list, storage ratio, etc.
But no problem, we will be more strict and ask more questions on the relevant points in the future.

> None SP matches the provided list.


When clients actually stored, the SP they work with changed. We think it is a very reasonable situation, so there is no restriction on it. However, we will strengthen the check in the future.
3.[PolarGeospatial Center](https://github.com/PluskitOfficial/bookkeeping/issues/9)

> data was stored several times before DataCap Application 1/2
> DataCap Application 2/2. The client said they think their data are the most up to date. What they based this on? Did they check that somehow? 


The client has done a simple search on Github, but there may be a problem with the query method, and they do not see the same data, so they think it is the latest.

> Did I understand correctly it is about amount of data storage within one SP? If so, this is a factor that depends on the number of granted allocations, being at 20% with the final allocation. I think more explanation might be needed here. 


Our requirement is that the same batch of data, in the same batch of storage procedures after an allocation, the proportion of storage in each node shall not more than 30%. This is how we ask our clients.
Beside, we cannot specify the correspondence between the node and sp, so we use the node as a reference.

> All updated SPs match the latter list, yet 5 SPs weren’t updated on the GitHub.


The client did not update in time, we would supervise.

> 3 SPs have very low retrieval. 


At that time, we did not pay special attention to this problem, but we have paid special attention to the following clients. 
In addition, we will also ask about this question as soon as possible.
4.[NREL](https://github.com/PluskitOfficial/bookkeeping/issues/11)

> dataset was stored before. Reference.


Before, it wasn't clear how to check if a data set was stored multiple times. We'll pay attention in the future.

> 1 out of 4 SPs has retrieval of 0%.


We asked the client to explain the issue at the time (available on Github), and they responded that the Sp was fixing their program and retrieval rates were recovering. We will continue to follow up.
5.[DN Data Coordination and Integration Center](https://github.com/PluskitOfficial/bookkeeping/issues/13)

> this dataset was stored before (top 3 results) Reference.


Before, it wasn't clear how to check if a data set was stored multiple times. We'll pay attention in the future.

> 2 SPs don’t match the provided list. 


We thought it was a very reasonable situation, so there was no restriction on it. However, we will strengthen the check in the future.

> 1 SP has retrieval of <1%.


We asked the client to explain the issue at the time (available on Github), and they responded that "some Sps’ networks are unstable, resulting in lower retrieval rates than others."We will continue to follow up.

**Comment by PluskitOfficial** [comment]
@filecoin-watchdog 
Thanks for your reply.

> This is not forbidden, but duplication must be properly justified (there is a place for this in the form). Besides, with so many duplicates it is hard to reasonably justify another copy of the same data. As an allocator, please, pay special attention to this.

Ok, no problem. We'll pay special attention to it later.

> In response to the SP change issue, it is fine for the client to use different SPs, but they must inform the allocator. This is the issue I am addressing, not the fact of changing SPs.

No problem, we will notify the clients and pay more attention to this in the future.

**Comment by galen-mcandrew** [comment]
Reviewing the above audit, as well as these reports: https://compliance.allocator.tech/report/f03019839/1733272802/report.md & https://filecoinpulse.pages.dev/allocator/f03019839/

Overall there is mixed evidence of diligence and compliance. Here are specific areas that need to improve for this next round:

- SP lists need to remain updated and accurate
- Decrease redundant datasets, monitor and intervene when CID sharing occurs
- Increase retrieval 

Given this mixed review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 2.5PiB of DataCap** from RKH, to allow this allocator to show increased diligence and alignment.

@PluskitOfficial please review your [application](https://github.com/filecoin-project/notary-governance/issues/1016) and work to improve the alignment.

**Comment by PluskitOfficial** [comment]
@galen-mcandrew Thanks Galen! We'll try to work harder to  improve the alignment.
