### ISSUE TITLE
Rotate signer on f080 Root Key Holder multisig

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/Allocator-Governance#226]
The Governance team has been asked to update a signer on the f080 Root Key Holder (RKH) multisig. This signer has been verified and passed KYC checks, and they will be onboarded over the next weeks. We will be leaving the previous address on during this onboarding process, in the event that we need to troubleshoot. Once we have completed onboarding, we will remove the previous address. 

This new address does not change the known and listed organizations, nor does it change the expectations or guidelines for Root Key Holders.

**Comment by lyjmry** [comment]
Hello @galen-mcandrew  .Do we need to wait a few weeks before renewing a round of allocator quotas?https://github.com/filecoin-project/Allocator-Governance/issues/214

**Comment by galen-mcandrew** [comment]
@lyjmry That is not directly related. Governance team is still reviewing compliance audits and making requests for refreshes.
