### ISSUE TITLE
2nd Community Review of IPFS Force Allocator

### ISSUE THREAD

**Issue by ipfsforcezuofu** [filecoin-project/Allocator-Governance#229]
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1034
first Community Diligence: https://github.com/filecoin-project/Allocator-Governance/issues/168

The data distribution and retrieval rates have significantly improved for the three clients. However, there remains a considerable gap between our DC capacity and their demands. We would appreciate your support in enhancing our service level to better meet our clients' needs. Thank you.

**Comment by filecoin-watchdog** [comment]
@ipfsforcezuofu 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1034)  
[Compliance Report](https://compliance.allocator.tech/report/f03019856/1732842640/report.md)  
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/168)  
1st Review score: 5PiB

5 PiB granted to existing clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| FileDriveLabs | 1PiB | Existing |
| AsiaTelevision Limited | 1PiB | New |
| DuitangInformation Technology (Shanghai) Co., Ltd. | 2.98PiB | New |

[FileDriveLabs](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/15) 
* The allocator has made significant improvements in the application, including clearer communication with the client and better documentation of discussions and arrangements.
* Could you clarify the new system for updating the SP list? From the thread, it seems that the client is required to update only the SPs they use. However, this approach might lead to incorrect assumptions that the client is not updating their SPs. Please explain the new system for maintaining an accurate SP list to ensure proper assessment.
* The client's retrieval rates appear to be very poor; this issue should be addressed with the client.

[AsiaTelevision Limited](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/21)
* This dataset was already stored: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2256. However, the client stated in the form that it had not been stored previously.
* All SPs match the provided list.
* Two SPs have very low retrieval rates.

[DuitangInformation Technology (Shanghai) Co., Ltd.](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/30)
* This client has not updated their SP list.
* The client declared 4 replicas, but there are already 7.

**Comment by galen-mcandrew** [comment]
Some mixed evidence above, and some specific issues that need to be resolved:

- extensive VPN usage without clear justification or accountability, across most clients
- low regional SP distribution, linked to the above
- inconsistent and low retrieval
- SP details not being updated or accurately maintained

We are seeing improvement and more clear communications, and expect these areas to continue to improve. Given this, we will request an **additional 5PiB of DataCap** from RKH to allow this allocator to show increased diligence and alignment.
