### ISSUE TITLE
2nd Community Review of SXX Future  Data Allocator

### ISSUE THREAD

**Issue by sxxfuture-official** [filecoin-project/Allocator-Governance#232]
Latest Allocator Report: https://compliance.allocator.tech/report/f03010963/1732151095/report.md
This round of review is the second round of 10PiBs allocations.

Current Clients:
![image](https://github.com/user-attachments/assets/e4696268-c87d-497a-a26e-afdf71bce418)

It took us several months to complete the allocation of 10PiB of Datacap in the last round. During this period, we have been looking for more suitable clients and reviewing compliant and reliable SPs.
There are currently four projects under sealing:
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/3
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/5
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/18
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/20
We are currently conducting KYC audits on some of the remaining.

In the Allocator workflow, we focus on the following aspects:
1. Verify the identity of the client, complete the KYC process, and examine the authenticity and rationality of the identity
2. Information transparency: We require the client to disclose SPs information in a timely manner, and this is a continuous action throughout the life cycle of LDN
3. Spark retrieval rate, we strictly require SPs to have a compliant retrieval rate, and nodes that do not meet the standard will be required to increase their retrieval rate within a limited time
4. The location dispersion of SPs, we require data to be distributed to different regions

We continue to support and participate in the filecoin+ project, and we will also prepare for the next batch of allocators.Thanks!

**Comment by filecoin-watchdog** [comment]
@sxxfuture-official 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1028)  
[Compliance Report](https://compliance.allocator.tech/report/f03010963/1733101768/report.md)  
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/53)  
1st Review score: 10PiB

10 PiB granted to existing clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| ResolutionRapid Refresh (HRRR) Model | 1PiB | Existing |
| Beijingkebike Education Consulting | 2PiB | Existing |
| NationalLibrary of Medicine | 4PiB | New |
| NOAA | 3PiB | New |

[ResolutionRapid Refresh (HRRR) Model](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/5)
* Retrieval rates are still unsatisfactory. 13 out of 24 SPs have retrieval rates of 0 or too low.
* The client declared 5 replicas, but there are already 11.
* Some SPs were never updated by the client. The newest updates to SPs have not yet been used for deals. The allocator should verify this.

[Beijingkebike Education Consulting](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/3)
* The client declared 10 replicas, but there are already 14.
* 19 out of 32 SPs have retrieval rates of 0 or too low.
* Some SPs were never updated by the client.

[NationalLibrary of Medicine](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/20)
* This dataset has already been stored multiple times: https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+sra-pub-src-1&type=issues
* The client should narrow the scope of the data they want to store again and explain why they want to store it again.
* The client declared 4 replicas of 1582TiB, totaling 6PiB, not 5PiB.
* Although 4 replicas were declared, there are already 11.
* Two SPs used for deals were not updated in the issue.
* In the allocator application, the allocator declared, “Our principle is to have nodes distributed across at least four different countries or regions, spanning at least two different continents.” This condition was not met, as all SPs are within one continent.
* Two SPs out of 11 have retrieval rates that are too low.

[NOAA](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/18)
* The client declared 5 replicas of 1221TiB, totaling 6PiB, not 5PiB.
* The client declared 5 replicas, but there are already 17.
* This dataset has already been stored multiple times: https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+noaa-nbm-pds&type=issues
* Five SPs out of 18 have retrieval rates that are too low.
* In the allocator application, the allocator declared, “Our principle is to have nodes distributed across at least four different countries or regions, spanning at least two different continents.” This condition was not met, as all SPs are within one continent.

**Comment by sxxfuture-official** [comment]
@filecoin-watchdog 
Thank you so much for your professional review of the LDN under the Allocator. We have conducted a more in-depth analysis of the questions you raised.

- About [ResolutionRapid Refresh (HRRR) Model](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/5) and [Beijingkebike Education Consulting](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/3), some SPs were never updated by the client.
This part is that the two LDNs have not yet been completed, and some SPs have just been sealing, and the client did not disclose it in time. In this regard, I asked the two clients to supplement and they quickly responded to this part of the information.
In the future, I will strengthen the supervision of SPs information updates.
![image](https://github.com/user-attachments/assets/548c3803-76b3-4ea3-ac36-7b45d33797c8)

- About some SPs retrieval rates of 0 or too low
I have always been concerned about the Spark retrieval rate, but as more SPs are involved, some SP with low retrieval rates have also appeared. After communicating with the client and SPs, I summarized the following reasons:
1. The sealing process of some SPs requires them to uniformly adapt the retrieval work after the sealing stage is completed, which will cause a certain lag in the retrieval rate.
2. The recent upgrade has caused a sharp drop in the original retrieve rate. They are already carrying out technical upgrades in this area, and it seems to have had very good results in the past two days.
![image](https://github.com/user-attachments/assets/6463d449-3c88-40dc-9df4-a878acab7167)
3. The node network in some areas fluctuates greatly or has high latency, resulting in low retrieval rates.

- The number of actual packaged replicas is greater than the number declared during application
The client has actively added SPs to support retrieval in the application. Due to the addition and replacement of SPs, the number of replicas is higher than the planned number. However, we support clients to replace SPs to show high retrieval rate.

- Regarding the issue that the SPs regions of the two latest LDNs are not dispersed enough
These two are new LDNs that have been started recently and are still in the process of actively sealing, so I cannot determine whether they are in violation of this point. However, I will urge the client to add more SPs from different regions in the next storage process and continue to monitor this.

- The dataset for the two latest LDNs has already been stored multiple times
We have verified that the data stored by clients is public data on AWS. We welcome you to store valid data.
We will conduct further inspections on the data stored by clients in subsequent work and require clients to promptly disclose the status of the stored data.

**Comment by galen-mcandrew** [comment]
Seeing mixed results overall, and appreciate the information provided. These specific areas need improvement:

- Accurate and updated SP lists
- Accurate regional distribution, with VPNs accounted for and explained
- Accurate and updated number of replicas
- Minimize duplicate and redundant datasets already existing on network

The biggest area for improvement though would be the overall retrievability of datasets. We have seen many clients, allocators, and SPs find success and demonstrate high SPARK retrieval scores by now. Given these flags, we are requesting an **additional 5PiB of DataCap** from RKH.

@sxxfuture-official please work to address the issues noted above as you continue to support public open datasets.

**Comment by sxxfuture-official** [comment]
@galen-mcandrew 
Thank you for your support!
I will focus on solving the above problems in my subsequent work.
