### ISSUE TITLE
2nd Community Review of ZCFIL+

### ISSUE THREAD

**Issue by zcfil** [filecoin-project/Allocator-Governance#234]
Previous review:https://github.com/filecoin-project/Allocator-Governance/issues/159

Previous round of DC continued to be allocated to existing clients
example 1:https://github.com/zcfil/ZCFIL/issues/3
example 2:https://github.com/zcfil/ZCFIL/issues/6

Ongoing reports are generated to observe the distribution and retrieval of data by clients

**Comment by filecoin-watchdog** [comment]
@zcfil 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1009)  
[Compliance Report](https://compliance.allocator.tech/report/f03014659/1733184133/report.md)  
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/159#issuecomment-2363622944)  
1st Review score: 5PiB

5 PiB granted to existing clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| AllenInstitute | 3PiB | Existing |
| FengwoExtraordinary | 2PiB | Existing |

[AllenInstitute](https://github.com/zcfil/ZCFIL/issues/3)
*3 out of 9 SPs have retrieval rate of 0%

[FengwoExtraordinary](https://github.com/zcfil/ZCFIL/issues/6) 
*9 of 15 SPs Have too low retrieval rate. 
*All SPs match the provided or updated list. 
*The client has sealed too many replicas. The allocator already ask the client for clarification.

**Comment by filecoin-watchdog** [comment]
@zcfil 
I'll let myself share my point of view on this matter:
You’ve already addressed this with the customer, and they’ve promised to follow the rules. If the issue happens again, you’ll have strong grounds to reject them and end the application. 
Personally, I believe giving the customer a warning is better than fully cancelling support at this stage. 
However, the final decision is yours. I won’t judge your choices as long as they comply with Filecoin rules and your allocator application.

**Comment by galen-mcandrew** [comment]
Echoing what is covered above: the decision to support or reject a client is up to the allocator. That decision, and the allocator's justification, impacts the GovTeam's overall compliance review of the allocator. I agree that monitoring, intervening, and offering clear public & accountable warnings is better than fully rejecting for any discrepancy. That said, these are the types of issues and evidence that would be even better for you, the allocator, to present when opening a community review. It will always look better to present all the evidence yourself, and it can help expedite the investigation.

However, there are bigger issues that need to improve and be addressed going forward:
- Accurate regional distribution, with VPNs accounted for and explained
- Additional details regarding dataset preparation, especially when redundant datasets
- Increase retrieval scores: current average is ~30%

We have seen many clients, allocators, and SPs find success and demonstrate high SPARK retrieval scores by now. Given these flags, we are requesting an **additional 2.5PiB of DataCap** from RKH, to allow this allocator to show increased diligence and alignment.

@zcfil please note the above issues as you continue supporting these clients.
