### ISSUE TITLE
[DataCap Refresh] 2nd Review of TopBlocks

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/Allocator-Governance#245]
First Review https://github.com/filecoin-project/Allocator-Governance/issues/177

Allocator Compliance Report: [report](https://compliance.allocator.tech/report/f03019931/1733793038/report.md)

5PiBs DataCap awarded in 2nd round

example 1: https://github.com/filplus-bookkeeping/TopBlocks/issues/25    3PiB
example 2: https://github.com/filplus-bookkeeping/TopBlocks/issues/22   2PiB

**Comment by woshidama323** [comment]
For "Compliance Report" I am not sure why the average rate is "42%"
For the latest round 
Example1 :  https://check.allocator.tech/report/filplus-bookkeeping/TopBlocks/issues/25/1733814623825.md
Example2:   https://check.allocator.tech/report/filplus-bookkeeping/TopBlocks/issues/22/1733815150105.md

You can see that the retrieval rate is much higher than 42%

**Comment by Kevin-FF-USA** [comment]
Hi @woshidama323 and @peter6wei,

Wanted to suggest - for faster processing, using the new request TEMPLATE.  

Would require closing this issue, then opening a new request and completing the information in the New Issue Template
https://filecoinproject.slack.com/archives/C06MTBZ44P2/p1733863576779879

![image](https://github.com/user-attachments/assets/b27bda9b-5f13-497b-b574-9848090847f3)

**Comment by woshidama323** [comment]
Thanks for your kind reminder , Will raise a new one right now

**Comment by woshidama323** [comment]
Hey Kevin
Has finished with #252
