### ISSUE TITLE
[DataCap Refresh] <2nd> Review of <Allocator Antalpha>

### ISSUE THREAD

**Issue by nj-steve** [filecoin-project/Allocator-Governance#249]
Latest Compliance Report: https://compliance.allocator.tech/report/f03019858/1733967069/report.md

Previous review：https://github.com/filecoin-project/Allocator-Governance/issues/110

Client 1: https://github.com/Antalpha-Web3/Ant-Steve/issues/11

Client 2: https://github.com/Antalpha-Web3/Ant-Steve/issues/9

Client 3: https://github.com/Antalpha-Web3/Ant-Steve/issues/5

**Comment by nj-steve** [comment]
Hi Governance Team:
The retrieval success rate looks nice and region of distribution also looks good.

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/953ae19a-ef0c-4c7a-8616-6ea73ec47b62" />

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/436f8282-1369-45aa-ac1a-63a8d4f457c4" />


Most SPs have been supporting retrieval, but some have been supporting retrieval for several months and no longer do so. For those that have not supported retrieval in the past week, we will notify the client and no longer send marketdeals to them.

**Comment by Kevin-FF-USA** [comment]
Hi @nj-steve,

Wanted to suggest - for faster processing, using the new request TEMPLATE.  

Would require closing this issue, then opening a new request and completing the information in the New Issue Template
https://filecoinproject.slack.com/archives/C06MTBZ44P2/p1733863576779879

![image](https://github.com/user-attachments/assets/b27bda9b-5f13-497b-b574-9848090847f3)
