### ISSUE TITLE
[Allocator Application] <ABC Inc>< ABC>

### ISSUE THREAD

**Issue by martapiekarska** [filecoin-project/Allocator-Governance#51]
*Allocator Application*

## Application Number
recUyCTjuVrCpkrvQ

## Organization Name 
ABC Inc

## Allocator Pathway Name
ABC

## Github PR Number
50

## Region of Operation
Africa,Asia minus GCR

## GitHub ID
martapiekarska

## On-chain address
f123456789

## Type of Allocator
Novel allocator not on RFA

## Filecoin Community Agreement
_As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, allocator, or other operating entity_
Acknowledge

## Type of Allocator and RFA List
RFA: Automated - GitHub

## Allocator Description
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Monetization and Fee structure
Client fees,SP fees. 

## Target Clients
Web3 developers,Commercial/Enterprise,Open/Public 

## Client Diligence Check
Automated deterministic

## Description of client diligence
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Type of data
Private encrypted with on-chain deal pricing

## Description of Data Diligence
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Data Preparation
IPFS Kubo

## Replicas required, verified by CID checker
2+

## Distribution required
Equal distribution of deals across regions

## Number of Storage Providers required
4+

## Retrieval Requirements
Public data highly retrievable over Spark. 

## Allocation Tranche Schedule TypeStandardized scaling tranche schedule.
100

## Will you use FIDL tooling, such as allocator.tech and other bots?
Yes, all available tools

## GitHub Bookkeeping Repo Link
github.com/martapiekarska

## Success metrics
Number of clients

## Timeline to begin allocating to clients
1 week from RKH approval

## Funnel: Expected DataCap usage over 12 months
5-50PiB

## Risk mitigation strategies
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Dispute Resolutions
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Compliance Audit Check
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Compliance Report content presented for audit
Client Diligence: Financial Audits and Credit Check reports,Client Diligence: KYC/KYB report on clients,Data Compliance: Proof of provenance report. 

## Connections to Filecoin Ecosystem
Previous allocator,Previous notary,Code contributor

## Slack ID
mpg

**Comment by galen-mcandrew** [comment]
Test, closing.
