### ISSUE TITLE
Community Diligence Review of Niwan Dao Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#52]
Review of Allocations from @Niwan-dao
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1081

First example:
DataCap was given to:
https://github.com/NiwanDao/NiwanPathway/issues/10

Public Open Dataset - key compliance requirement: Retrievability

1st point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application - need gov team to investigate details
Client asked for 10PiB and 1PiB of DataCap given to brand new GitHub ID. 

2nd point)
Client said these were the SPs
Hainan future cloud Technology Co., f02933536, Ningxia
Hainan future cloud Technology Co., f02933563 ,Ningxia
Siwei Technology Co.,Technology Co.,f03083319, Chengdu
Youyun Tech,tobecreated, Hongkong 
qitian yun ,tobecreated, nanjing

Actual data storage report:
https://check.allocator.tech/report/NiwanDao/NiwanPathway/issues/10/1716967283901.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f03083319 | Qingdao, Shandong, CNHangzhou Alibaba Advertising Co.,Ltd. | 393.41 TiB | 100.00% | 393.41 TiB | 0.00% | 0.00%

One SP ID has sealed 40% of deals
Additional diligence needed to confirm storage plan 

Finally, 0% retrievability for an open dataset

**Comment by filecoin-watchdog** [comment]
Next example:
https://github.com/NiwanDao/NiwanPathway/issues/7

Client again unknown, asked for 10PiB was given 1PiB. - Gov team needs to check client KYC KYB. Not clear from application.

Same trend as before, only one storage provider 
Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f01782100 | Nanjing, Jiangsu, CNJiangsu Wuxi International IDC network | 11.28 TiB | 100.00% | 11.28 TiB | 0.00%

Finally, 0% retrievability for an open dataset

**Comment by filecoin-watchdog** [comment]
Third example:
https://github.com/NiwanDao/NiwanPathway/issues/1 

Client is the Allocator. Gave themself two allocations - 500TiBs and 1000 TiBs

One SP has sealed 40%+ of the deals

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f02933563 | Yinchuan, Ningxia, CNCHINANET NINGXIA province ZHONGWEI IDC network | 148.94 TiB | 4.03% | 148.94 TiB | 0.00% | 0.00%
f02933536 | Yinchuan, Ningxia, CNCHINANET NINGXIA province ZHONGWEI IDC network | 128.81 TiB | 3.48% | 128.81 TiB | 0.00% | 0.00%
**f02889390 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 1.58 PiB | 43.65% | 1.58 PiB | 0.00% | 0.00%**
f01946104 | Chengdu, Sichuan, CNCHINANET-BACKBONE | 660.00 TiB | 17.85% | 660.00 TiB | 0.00% | 0.00%
f02035252 | Chengdu, Sichuan, CNCHINANET-BACKBONE | 408.47 TiB | 11.05% | 408.47 TiB | 0.00% | 0.00%
f01225783 | Chengdu, Sichuan, CNCHINANET-BACKBONE | 50.00 TiB | 1.35% | 50.00 TiB | 0.00% | 0.00%
f02966277new | Singapore, Singapore, SGGoDaddy.com, LLC | 445.09 TiB | 12.04% | 445.09 TiB | 0.00% | 0.00%
f03083319 | Qingdao, Shandong, CNHangzhou Alibaba Advertising Co.,Ltd. | 242.50 TiB | 6.56% | 242.50 TiB | 0.00% | 0.00%

SPs - applicant said this is a continuation of a previous project: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2300

Retrieval success rate = 0%

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is **not** in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/1081).

Specifically: 

- No evidence of diligence with client (no verification of client claims)
- Allocations did not match tranche schedule (not scaling trust over time)
- Subsequent allocations given despite noncompliant client deal-making (no verification of data legitimacy)
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

**Given these details, this allocator will not receive a subsequent allocation request to the root key holders at this time.**

**Comment by Kevin-FF-USA** [comment]
Hi @NiwanDao ,

Shifting our Slack DM here for easier threading. The behavior in the distributions didn't follow any of the framework that was outlined in the application. Taking into account your length as a Notary in the past I changed the label from `audit in process` to `Needs Governance` to have a final review of the information you provided and if it accounts for the diligence discrepancies.   

In the meantime, linking to any updated Bookkeeping you've done, or Retrieval % would benefit the case for diligence compliance progress.

**Comment by Kevin-FF-USA** [comment]
Hi @NiwanDao 
Wanted to follow up on this, had left it open for some time while we processed other renewals and received new pathway applications.  Unable to secure additional Datacap for this pathway given the issues in maintaining compliance, but if interested in returning as an Allocator in the future, here are the steps for re-applying. 
https://blog.allocator.tech/2024/05/rolling-applications-are-open-for.html

Since there are already 60+ active pathways that are doing Manual Reviews, only prioritizing the applications which are building tooling under a different pathway than Manual.  Here is a blog with additional details https://blog.allocator.tech/2024/04/allocator-tech-blog.html
