### ISSUE TITLE
Community Diligence Review of SXXFuture Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#53]
Review of Allocations from @sxxfuture-official
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1028

First example:
DataCap was given to:
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/3

Public Open Dataset - key compliance requirement: Retrievability

1st point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application - need gov team to investigate details

2nd point)
Client said these were the SPs
f02900009 - Singapore
f03000035 - China,Hubei
f03028310 - HongKong
f03028326 - HongKong
f02944782 - US

Actual data storage report:
https://check.allocator.tech/report/sxxfuture-official/filplus-allocator-sxxfuture/issues/3/1717007284444.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f03074592 | Los Angeles, California, USCNSERVERS LLC | 93.75 TiB | 4.21% | 93.75 TiB | 0.00% | 0.00%
**f03028326** | Shenzhen, Guangdong, CNCTGNet | 187.50 TiB | 8.41% | 187.50 TiB | 0.00% | 0.00%
f02830476 | Shenzhen, Guangdong, CNCTGNet | 93.69 TiB | 4.20% | 93.69 TiB | 0.00% | 0.00%
f03074586 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 186.34 TiB | 8.36% | 186.34 TiB | 0.00% | 0.00%
f03074589 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 91.50 TiB | 4.11% | 91.50 TiB | 0.00% | 0.00%
**f03028310** | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 58.34 TiB | 2.62% | 58.34 TiB | 0.00% | 0.00%
f03028325 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 53.97 TiB | 2.42% | 53.97 TiB | 0.00% | 0.00%
f02953066 | Los Angeles, California, USIPTELECOM ASIA | 137.66 TiB | 6.18% | 137.66 TiB | 0.00% | 70.47%
f02837684new | Hong Kong, Hong Kong, HKIPTELECOM Global | 140.41 TiB | 6.30% | 140.41 TiB | 0.00% | 53.57%
f02956073 | Singapore, Singapore, SGIPTELECOM Global | 93.63 TiB | 4.20% | 93.63 TiB | 0.00% | 0.00%
f03074587 | Seoul, Seoul, KRMOACK.Co.LTD | 187.47 TiB | 8.41% | 187.47 TiB | 0.00% | 0.00%
f03074583 | Tokyo, Tokyo, JPNearoute Limited | 187.50 TiB | 8.41% | 187.50 TiB | 0.00% | 0.00%
f03028321 | Tokyo, Tokyo, JPNearoute Limited | 62.50 TiB | 2.80% | 62.50 TiB | 0.00% | 0.00%
f03080854 | Piscataway, New Jersey, USThe Constant Company, LLC | 280.69 TiB | 12.60% | 280.69 TiB | 0.00% | 0.00%
f03080852 | Toronto, Ontario, CAThe Constant Company, LLC | 280.09 TiB | 12.57% | 280.09 TiB | 0.00% | 0.00%
f03044609 | Paripark, Seoul, KRThe Constant Company, LLC | 93.31 TiB | 4.19% | 93.31 TiB | 0.00% | 0.00%

Two SPs from original list match. Many additional SPs taking deals that need diligence to confirm storage plan

3rd Point) 0% retrievability on majority of SPs across three allocations of DataCap

**Comment by filecoin-watchdog** [comment]
2nd example:

DataCap was given to:
https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/5

Public Open Dataset - key compliance requirement: Retrievability

1st point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application - need gov team to investigate details

2nd point)
After a prompt from allocator, client said these were the SPs:
f02975857 Qomo Chongqing,China
f03028326 HKblockchain HK
f02837684 Xunlei HK
f02900009 HongLian WEB3 Hubei,China
f02956073 SG,Singapore Alice
f02953066 US,Los Angeles Bluesky

Actual data storage report:
https://check.allocator.tech/report/sxxfuture-official/filplus-allocator-sxxfuture/issues/5/1717043837772.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
**f02975857** | Tianjin, Tianjin, CNCHINA UNICOM China169 Backbone | 33.34 TiB | 2.63% | 33.34 TiB | 0.00% | 0.00%
f03074592 | Los Angeles, California, USCNSERVERS LLC | 93.75 TiB | 7.40% | 93.75 TiB | 0.00% | 0.00%
**f03028326** | Shenzhen, Guangdong, CNCTGNet | 93.75 TiB | 7.40% | 93.75 TiB | 0.00% | 0.00%
f03074589 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 181.31 TiB | 14.31% | 181.31 TiB | 0.00% | 0.00%
f03074586 | Hong Kong, Hong Kong, HKHong Kong Beecloud System Technology Services Limited | 93.44 TiB | 7.38% | 93.44 TiB | 0.00% | 0.00%
**f02953066** | Los Angeles, California, USIPTELECOM ASIA | 45.09 TiB | 3.56% | 45.09 TiB | 0.00% | 69.93%
**f02956073** | Singapore, Singapore, SGIPTELECOM Global | 93.69 TiB | 7.40% | 93.69 TiB | 0.00% | 0.00%
**f02837684** | Hong Kong, Hong Kong, HKIPTELECOM Global | 31.31 TiB | 2.47% | 31.31 TiB | 0.00% | 46.59%
f03074587 | Seoul, Seoul, KRMOACK.Co.LTD | 93.75 TiB | 7.40% | 93.75 TiB | 0.00% | 0.00%
f03074583 | Tokyo, Tokyo, JPNearoute Limited | 93.75 TiB | 7.40% | 93.75 TiB | 0.00% | 0.00%
f03080852 | Toronto, Ontario, CAThe Constant Company, LLC | 187.19 TiB | 14.78% | 187.19 TiB | 0.00% | 0.00%
f03080854 | Piscataway, New Jersey, USThe Constant Company, LLC | 187.13 TiB | 14.77% | 187.13 TiB | 0.00% | 0.00%
**f02900009**new | UnknownUnknown | 39.38 TiB | 3.11% | 39.38 TiB | 0.00%

Several SPs match per the list, the remaining need diligence to confirm entity and location.

Retrievals showing from two SPs. all others 0%

**Comment by sxxfuture-official** [comment]
First example:
The client updates the SP information after the second and third rounds respectively:
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/c8b8d476-5e48-4a47-8828-91b7d8f06880)
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/bba169f6-da2e-44cc-9940-1541bec04e64)

**Comment by sxxfuture-official** [comment]
Second example:
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/e4853494-f4ba-46c7-829a-1ff81b90a822)

**Comment by galen-mcandrew** [comment]
Based on an additional compliance review, it appears this allocator is attempting to work with public open dataset clients. 

**However, the data associated with this pathway is not currently able to be retrieved at scale, and testing for retrieval is currently noncompliant.**

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

Before we will submit a request for more DataCap to this allocator, please verify that you will **instruct, support, and require** your clients to work with retrievable storage providers.

**@sxxfuture-official can you verify that you will enforce retrievability requirements, such as through Spark?**

**Comment by sxxfuture-official** [comment]
@galen-mcandrew 
Thank you for reviewing my previous work!
Continuously improving the node search problem is also my recent focus. At present, there are many nodes with a 0% SPARK search rate. I have communicated with clients and SPs. The feedback I have received is that traditional graphsy and http searches can be performed, but SPARK searches are not well understood.
I continue to urge the client to follow up and solve the SPARK search problem.
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/023ae3d2-c566-418e-b0ae-1cf3e9b238be)
I have consulted many technical staff for this purpose, and now I can basically determine the following prerequisites for SPARK retrieval:
- Miner adds configuration:
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/e3d3a505-e5d4-4f6c-ac2b-2fd2a8afa5e6)
- You can query the node information through peerid at https://cid.contact/providers

It is worth affirming that many SPs under the current distributor have achieved considerable results：
![image](https://github.com/filecoin-project/Allocator-Governance/assets/113963951/b7a18823-a7dc-477c-bcbc-69d87fca9c91)

**Comment by sxxfuture-official** [comment]
I will continue working on this area to ensure that the vast majority of SPs can successfully support SPARK retrieval.
