### ISSUE TITLE
Community Diligence Review of Top Value Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#7]
Review of Top Value Allocations from @luobin544

Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1013

**First example:**
DataCap was given to: 
https://github.com/TVLimited/top-value-storage/issues/11

Public Open Dataset - key compliance requirement: Retrievability

1st point) 
No sign of KYC or KYB of client or dataset as mentioned in allocator application

2nd point)
Client said these were the SPs
1.f02813403 UK
2.f02814393 US
3.f02830321 VN
4.f02837226 UK
5.f02864300 US

Actual data storage report:
https://check.allocator.tech/report/TVLimited/top-value-storage/issues/11/1714392341259.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
f02837226 | London, England, GBBinary Racks Limited | 471.97 TiB | 23.05% | 471.97 TiB | 0.00%
f02813403 | London, England, GBBinary Racks Limited | 423.00 TiB | 20.66% | 423.00 TiB | 0.00%
f02814393 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 434.50 TiB | 21.22% | 434.50 TiB | 0.00%
f02864300 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 277.31 TiB | 13.55% | 277.31 TiB | 0.00%
f02830321 | Ho Chi Minh City, Ho Chi Minh, VNVNPT Corp | 440.50 TiB | 21.52% | 440.50 TiB | 0.00%

These SP IDs match per reports. 

Additional diligence needed to confirm actual storage locations

3rd point)
Second allocation awarded to this client. 
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability. 

The Allocator showed no sign of diligence after 1st allocation of 1PiB where 0% retrievability was known and gave the 2nd allocation of 1PiB to the client.

**Comment by filecoin-watchdog** [comment]
**Second example:**
The allocator gave DataCap to an additional client:
https://github.com/TVLimited/top-value-storage/issues/13


Public Open Dataset - key compliance requirement: Retrievability

1st point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application

2nd point)
Client said these were the SPs

f02096851 Indonesia
f02828509 Korea
f02812781 Vietnam
f02886019 Canada
f02843151 Turkey

https://check.allocator.tech/report/TVLimited/top-value-storage/issues/13/1715176645591.md

However, Actual data storage report:
https://check.allocator.tech/report/TVLimited/top-value-storage/issues/11/1714392341259.md

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
f02837226 | London, England, GBBinary Racks Limited | 471.97 TiB | 23.05% | 471.97 TiB | 0.00%
f02813403 | London, England, GBBinary Racks Limited | 423.00 TiB | 20.66% | 423.00 TiB | 0.00%
f02814393 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 434.50 TiB | 21.22% | 434.50 TiB | 0.00%
f02864300 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 277.31 TiB | 13.55% | 277.31 TiB | 0.00%
f02830321 | Ho Chi Minh City, Ho Chi Minh, VNVNPT Corp | 440.50 TiB | 21.52% | 440.50 TiB | 0.00%

These SP IDs do not match. Although they are actually the same SPs from the first application above

Additional diligence needed to confirm actual storage locations

3rd point)
Second allocation awarded to this client.
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability.

The Allocator showed no sign of diligence after 1st allocation of 1PiB where 0% retrievability was known and gave the 2nd allocation of 1PiB to the client.

**Comment by filecoin-watchdog** [comment]
Overall:
Three clients were awarded DataCap. Each client received initial tranche of 1PiB, which does match what was listed in the allocation application.

All three clients used the same 5 SP miner IDs. All SPs are not available for retrievals on open datasets. Compliance not met and 5 PiBs of DataCap awarded.

**Comment by Kevin-FF-USA** [comment]
Hi @luobin544

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/7.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/851b1457-6d8e-445a-a34f-cae3585241f7)

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is **not** in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/1013).

Specifically: 

- No evidence of diligence with client (no verification of client claims)
- Allocations did not match tranche schedule (not scaling trust over time)
- Subsequent allocations given despite noncompliant client deal-making (no verification of data legitimacy)
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

**Given these details, this allocator will not receive a subsequent allocation request to the root key holders at this time.**
