### ISSUE TITLE
Community Diligence Review of Origin Storage Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#8]
Review of Top Value Allocations from @tom-originstorage

Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1012

First example:
DataCap was given to:
https://github.com/Origin-Storage-IO/future-storage/issues/5

Public Open Dataset - key compliance requirement: Retrievability

1st point)
No sign of KYC or KYB of client or dataset as mentioned in allocator application

2nd point)
Client said these were the SPs
f02041085，Japan，TopValue 
f02813403 rimington Britain 
f02828509 hs88 Korea 
f02048990，Hong Kong，HS88

Actual data storage report:
https://check.allocator.tech/report/Origin-Storage-IO/future-storage/issues/5/1715259157530.md

f02837226 | London, England, GBBinary Racks Limited | 527.00 TiB | 20.91% | 527.00 TiB | 0.00%
f02813403 | London, England, GBBinary Racks Limited | 435.69 TiB | 17.28% | 435.69 TiB | 0.00%
f02864300 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 530.00 TiB | 21.02% | 530.00 TiB | 0.00%
f02814393 | Hanover, New Jersey, USITGLOBAL.COM NL B.V. | 494.94 TiB | 19.63% | 494.94 TiB | 0.00%
f02830321 | Ho Chi Minh City, Ho Chi Minh, VNVNPT Corp | 533.19 TiB | 21.15% | 533.19 TiB | 0.00%

These SP IDs taking deals do not match per report.

Additional diligence needed to confirm entity and actual storage locations

3rd point)
Second allocation awarded to this client.
However, per [Spark dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1&from=1709477321031&to=1713841165807), all SPs are either not available or have 0% retrievability.

The Allocator showed no sign of diligence after 1st allocation of 1PiB where 0% retrievability was known and gave the 2nd allocation of 1PiB to the client.

**Comment by filecoin-watchdog** [comment]
Interesting notes:
- The clients ([example](https://github.com/Origin-Storage-IO/future-storage/issues/3)) and SPs used on these client applications are the same as [Top Value Storage](https://github.com/filecoin-project/Allocator-Governance/issues/7) Allocator
- The allocator also signed for 5.85PiBs (more than available to allocate) on an initial allocation to the same client https://github.com/Origin-Storage-IO/future-storage/issues/10

**Comment by Kevin-FF-USA** [comment]
Hi @lifezou; @chainupk, @Tom-OriginStorage

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/8.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/b421d3a8-d8be-4a92-a06d-e2800fbe7ebf)

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is **not** in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/1012).

Specifically: 

- No evidence of diligence with client (no verification of client claims)
- Allocations did not match tranche schedule (not scaling trust over time)
- Subsequent allocations given despite noncompliant client deal-making (no verification of data legitimacy)
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

**Given these details, this allocator will not receive a subsequent allocation request to the root key holders at this time.**

**Comment by chainupk** [comment]
Hi,

Here are our responses:

- No evidence of diligence with client (no verification of client claims)

Internally, the KYC on the client was completed before the allocator pathway, therefore no new KYC was completed. We think this is where the shortfall is. Do let us know if we are required to just furnish the client's name. "We will store our client's information on Github and private emails and our own data storage facility. Whereas for the actual bookkeeping, we have a custom programmed excel sheet that our operations keep track of." as per our application. https://github.com/filecoin-project/notary-governance/issues/1012


- Allocations did not match tranche schedule (not scaling trust over time)
This is indeed a mishandled situation on our end. And we will rectify with the team on this.

- Subsequent allocations given despite noncompliant client deal-making (no verification of data legitimacy)
The is in the KYC process, mentioned in our application, "we implement periodic reviews and audits to ensure continued compliance with data ownership and legitimacy." As of current, the periodic reviews for this client were not yet triggered by our compliance department.

- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)
The team is looking into this, we will provide an appropriate response asap.

@galen-mcandrew thank you

Sincerely
Kenneth
