### ISSUE TITLE
Community Diligence Review of HashTeam Allocator

### ISSUE THREAD

**Issue by hash889900** [filecoin-project/Allocator-Governance#99]
Review of Allocations from HashTeam
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1050

First example:
DataCap was given to:
https://github.com/hash889900/HashTeam/issues/3

First: 256TiB • Second:512TiB • Third: 1PiB • Fourth:2PiB 
Due diligence was conducted before each signing. Pay close attention to Spark data, SP disclosure, etc.Screenshot below
![image](https://github.com/user-attachments/assets/0e244880-20da-4825-9bb5-57677f574acc)

SP disclosure：
f02866666 /ip4/103.160.100.187/tcp/6666 Tokyo
f03144777 /ip4/103.160.100.187/tcp/44777 Tokyo
f02820000 /ip4/14.215.165.46/tcp/15890 GuangZhou
f02639655 /ip4/113.96.22.206/tcp/6789 GuangZhou
f02588263 /ip4/103.201.24.43/tcp/5232 Hong Kong

Actual data storage report:
https://check.allocator.tech/report/hash889900/HashTeam/issues/3/1721384980892.md
![image](https://github.com/user-attachments/assets/8e2094ed-4a40-476c-8acd-c8d1f108e175)

All support spark retrieval and the overall retrieval rate has been increasing

Second example

DataCap was given to:
https://github.com/hash889900/HashTeam/issues/8

First: 256TiB
Due diligence was conducted before each signing. Pay close attention to Spark data, SP disclosure, etc.Screenshot below
![image](https://github.com/user-attachments/assets/aa979df4-f4dc-4e83-a304-5e290fa637ac)

SP disclosure：
f01930832 /dns4/1f4952i942.iok.la/tcp/24001 （112.86.232.91） Nanjin
f01390330 /ip4/113.132.177.9/tcp/24001 Xi an
f02899169 /ip4/113.132.177.9/tcp/25001 Xi an
f01888808 /ip4/86.123.188.55/tcp/25001 Romania

Actual data storage report:
https://check.allocator.tech/report/hash889900/HashTeam/issues/8/1721289192197.md
![image](https://github.com/user-attachments/assets/b0e0a12e-e261-4487-8c47-1e0e855a808d)

If you have any questions or suggestions, please leave a message, thank you!

**Comment by filecoin-watchdog** [comment]
https://compliance.allocator.tech/report/f03014732/1721396541/report.md

**Comment by hash889900** [comment]
https://compliance.allocator.tech/report/f03014732/1722224202/report.md

Report updated again, retrieval rates are steadily improving

**Comment by hash889900** [comment]
@Kevin-FF-USA @filecoin-watchdog @galen-mcandrew I see that the list is out, so can you ask what's wrong here?

**Comment by hash889900** [comment]
https://compliance.allocator.tech/report/f03014732/1722567568/report.md
Report updated again
But it looks like this report has the wrong retrieval rate
![image](https://github.com/user-attachments/assets/b5b80ab0-d615-4b93-9168-a642b5e84260)

Here's  bot report from the repo.
https://check.allocator.tech/report/hash889900/HashTeam/issues/3/1722567088482.md
![image](https://github.com/user-attachments/assets/1ce9f978-b2ad-4add-b9e7-b84a34cfa3e6)

https://check.allocator.tech/report/hash889900/HashTeam/issues/8/1722567163946.md
![image](https://github.com/user-attachments/assets/c4fe097b-bbc2-4f2e-ab92-24a4bcc9c089)

**Comment by hash889900** [comment]
The latest report so far, the customer explained that due to the new version update, there was a little problem with boostd connectivity, the fault lasted for a few days, so it caused the retrieval rate to drop, and it has been fixed now.You can see that the retrieval rate of the new SPs added by the client has been increasing.You can see that retrieval rates are continuing to improve
![image](https://github.com/user-attachments/assets/a338e851-69cf-491a-80c3-7ecd5353d759)

Here are the 24-hour retrieval rates for the five additional SPs
![image](https://github.com/user-attachments/assets/48508812-2171-4f7b-86d8-977ff90002b8)

**Comment by galen-mcandrew** [comment]
Based on an additional compliance review, this allocator is currently working with public open dataset clients. Additionally, the data associated with this pathway is starting to be able to be retrieved at scale, and testing for retrieval is currently increasing. We are also seeing diligence and interventions from the allocator to the client. 

This allocator is currently mostly working with a single client, which appears to be using some [VPN-hosted SPs](https://check.allocator.tech/report/hash889900/HashTeam/issues/8/1724037422997.md). According the allocator's application, they would require some additional details in the event that a client is working with these kinds of SPs ([question 28](https://github.com/filecoin-project/notary-governance/issues/1050#issuecomment-1890612486)). **Can you please provide some evidence of your diligence into this client's SPs?**

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

We also hoping to increase the allocator's role in supporting consistent data preparation, especially for public open datasets. There have been some conversations about increasing diligence, such as [more comprehensive questions](https://github.com/filecoin-project/Allocator-Governance/issues/125). **In what ways are you investigating your clients' data preparation and distribution?**

Depending on replies to the above and any additional details from the allocator, we would like to request **an additional 5PiB of DataCap.**

**Comment by hash889900** [comment]
>Can you please provide some evidence of your diligence into this client's SPs?

Here are some comments as well as screenshots
https://github.com/hash889900/HashTeam/issues/3#issuecomment-2196681610
![image](https://github.com/user-attachments/assets/041cea96-5c00-4c6f-acff-afa10d6e82cd)

https://github.com/hash889900/HashTeam/issues/8#issuecomment-2219721349
![image](https://github.com/user-attachments/assets/c5c6a84a-f61c-43a1-822d-223b1bd9ecd6)

>We also hoping to increase the allocator's role in supporting consistent data preparation, especially for public open datasets. There have been some conversations about increasing diligence, such as https://github.com/filecoin-project/Allocator-Governance/issues/125. In what ways are you investigating your clients' data preparation and distribution?

will adopt part of the questions posed in #125 to investigate client data preparation and distribution.

@galen-mcandrew thanks
